# Файл: localization.py

# Словарь, где хранятся все переводы.
TRANSLATIONS = {
    'ru': {
        # --- Общие ---
        'language_prompt': "Пожалуйста, выберите язык:",
        'language_changed': "✅ Язык изменен на Русский.",
        'back_button': "◀️ Назад",
        'cancel_button': "❌ Отмена",
        'confirm_button': "✅ Подтвердить",
        'error_generic': "❌ Произошла ошибка.",
        'unauthorized_action': "⛔️ У вас нет прав для выполнения этого действия.",
        'data_not_found_error': "Произошла ошибка, данные не найдены. Попробуйте снова.",
        'loading_please_wait': "⏳ Пожалуйста, подождите...",
        'action_cancelled': "Действие отменено.",
        'page_of': "Страница {page} из {total_pages}",
        'yes_button': "✅ Да",
        'no_button': "❌ Нет",
        'skip_button': "⏩ Пропустить",

        # show_profile
        'level_field': "▪️ Уровень:",
        'all_disciplines': "Все",
        'error_unauthorized': "❌ Не удалось определить вашу роль. Попробуйте авторизоваться снова.",

        'auth_role_approved_user': "🎉 Ваша роль «{role}» подтверждена!",

        # --- Главное меню ---
        'main_menu_title': "🏠 Главное меню",
        'submit_roster_button': "📋 Подать табель на сегодня",
        'form_report_button': "📝 Формировать отчет",
        'view_reports_button': "📊 Посмотреть отчеты",
        'profile_button': "👤 Профиль",
        'auth_button': "🔐 Авторизоваться",
        'manage_button': "⚙️ Управление",
        'reports_group_button': "➡️ Перейти в группу отчетов",
        'roster_summary_today': "\n\n📋 *Табель на сегодня:*",
        'roster_composition': "▪️ *Состав:* {details}",
        'total_declared': "▪️ *Всего заявлено:* {total} чел.",
        'completion_status': "\n\n📊 *Статус выполнения:*",
        'assigned_in_reports': "▪️ Задействовано в отчетах: *{assigned}* чел.",
        'free_in_reserve': "▪️ Свободно в резерве: *{reserve}* чел.",

        # --- Регистрация и Профиль ---
        'auth_prompt_role': "🔐 *Выберите вашу будущую роль:*",
        'auth_role_manager': "Руководитель",
        'auth_role_foreman': "Бригадир",
        'auth_role_pto': "ПТО",
        'auth_role_kiok': "КИОК",
        'auth_prompt_name': "📝 *Введите ваше имя и фамилию через пробел* (например: Иван Иванов):",
        'auth_error_name': "❗ *Ошибка: Введите и имя, и фамилию через пробел.*\n\n📝 *Пожалуйста, повторите ввод:*",
        'auth_prompt_contact': "📞 *Отлично! Теперь нажмите на кнопку ниже, чтобы отправить ваш контакт.*",
        'auth_contact_button': "📞 Отправить мой контакт",
        'auth_prompt_manager_level': "⚙️ *Последний шаг: выберите ваш уровень руководства:*",
        'auth_manager_level1': "Уровень 1 (полный доступ)",
        'auth_manager_level2': "Уровень 2 (по дисциплине)",
        'auth_prompt_discipline': "⚙️ *Последний шаг: выберите вашу дисциплину для роли «{role}»:*",
        'auth_prompt_discipline_manager': "⚙️ *...и вашу дисциплину для Уровня 2:*",
        'auth_pending_approval': "✅ *Данные приняты.*\n\n*Ваш запрос отправлен на подтверждение. Ожидайте...*",
        'auth_request_title': "🔐 *Запрос на регистрацию*",
        'auth_request_rejected_user': "❌ *Ваш запрос на роль «{role}» был отклонен.*",
        'auth_request_approved_admin': "✅ *Роль «{role}» для {name} подтверждена.*",
        'auth_request_rejected_admin': "❌ *Запрос для {name} отклонен.*",
        'profile_title': "👤 Ваш профиль:",
        'user_id_field': "▪️ UserID:",
        'phone_field': "▪️ Телефон:",
        'username_field': "▪️ Username:",
        'role_field': "▪️ Роль:",
        'brigade_field': "▪️ Бригада:",
        'discipline_field': "▪️ Дисциплина:",
        'level_field': "▪️ Уровень:",
        
        # --- Создание Отчета ---
        'report_step1_discipline': "📝 *Шаг 1: Для какой дисциплины создается отчет?*",
        'report_step1_corpus': "📝 *Шаг 1: Выберите корпус*",
        'report_step2_work_type': "📝 *Шаг 2: Выберите вид работ для «{discipline}»*",
        'report_step3_people_count': "📝 *Шаг 3: Укажите количество человек на объекте*",
        'report_step4_volume': "📝 *Шаг 4: Укажите выполненный объем в {unit}:*",
        'report_step4_volume_no_unit': "📝 *Шаг 4: Укажите выполненный объем:*",
        'report_step5_date': "📝 *Шаг 5: Выберите дату или введите ее вручную (ДД.ММ.ГГГГ)*",
        'report_step6_notes_prompt': "📝 *Шаг 6: Хотите добавить примечание?*\n_(номер чертежа, оси, проблемы и т.д.)_",
        'report_add_note_button': "✅ Да, добавить",
        'report_final_confirmation_title': "📋 *Проверьте и подтвердите ваш отчет:*\n",
        'report_confirm_and_send_button': "✅ Подтвердить и отправить",
        'report_error_no_roster': "⚠️ *Сначала нужно подать табель на сегодня!* \n\nВоспользуйтесь кнопкой в главном меню, чтобы заявить состав вашей бригады.",
        'report_error_no_people': "❌ *Ошибка!* Вы пытаетесь задействовать *{count}* чел., но в резерве осталось только *{reserve}*.\n\nВведите корректное число.",
        'report_note_prompt': "✍️ Введите ваше примечание одним сообщением:",
        'report_saved_and_sent': "✅ Отчет успешно сохранен и отправлен!",
        'report_saved_not_sent_error': "⚠️ *Отчет сохранен, но не может быть отправлен на согласование!*\n\nПричина: для дисциплины «*{discipline}*» не настроена тема в группе.\n\nПопросите администратора зайти в нужную тему и написать команду:\n`/link_topic {discipline}`",
        'report_new_from_foreman': "📄 *Новый отчет от бригадира: {foreman}* (ID: {report_id})\n",
        'report_status_pending': "*Статус:* ⏳ Ожидает согласования КИОК",
        'report_status_approved': "*Статус:* ✅ Согласовано: {approver}",
        'report_status_rejected': "*Статус:* ❌ Отклонено: {approver}",
        
        # --- Табель (Roster) ---
        'roster_already_submitted': "⚠️ Вы уже подавали табель на сегодня.",
        'roster_prompt': "📋 *Подача табеля на {date}*\n\nВведите количество человек для каждой должности **через запятую**, строго в указанном порядке.\nНапример, если у вас 5 сварщиков и 10 монтажников, введите: `5, 10`\n\n**Ваш порядок:**\n{roles_list}",
        'roster_confirm_prompt': "*Проверьте данные:*\n{summary}\n\n*Итого: {total} чел.*",
        'roster_confirm_and_save_button': "✅ Все верно, подтвердить",
        'roster_error_mismatch': "❌ *Ошибка!* Вы ввели {input_count} чисел, а ожидалось {expected_count}. Пожалуйста, введите количество для каждой должности из списка.",
        'roster_saved_safely': "✅ *Табель на сегодня успешно принят!*\n\nВ вашем резерве осталось *{reserve}* чел.",
        'roster_dangerous_save_warning': "‼️ *ВНИМАНИЕ!* ‼️\n\nВы пытаетесь заявить *{new_total}* чел., но в отчетах за сегодня уже задействовано *{assigned}* чел.\n\nПри подтверждении **все ваши отчеты за сегодня будут УДАЛЕНЫ**, и вам придется распределять людей заново.\n\nВы уверены, что хотите продолжить?",
        'roster_force_save_button': "✅ Да, удалить отчеты и сохранить",
        'roster_force_saved_success': "✅ *Ваши отчеты за сегодня были удалены. Новый табель принят!*",

       
        'forward_button': "Вперёд ▶️",
        'today_button': "Сегодня",
        'yesterday_button': "Вчера",

        'report_error_no_work_types': "⚠️ *Ошибка:* Не найдено ни одного вида работ для дисциплины «{discipline}».",

        'report_error_invalid_number': "❗*Ошибка:* Пожалуйста, введите количество человек одним положительным числом (например: 5).",
        'report_error_invalid_volume': "❗*Ошибка:* Пожалуйста, введите выполненный объем одним числом (можно дробным).",
        'report_error_invalid_date': "❗*Ошибка:* Неверный формат даты.\n\n📝 *Выберите дату кнопкой или введите ее вручную (ДД.ММ.ГГГГ)*",
        'report_summary_corpus': "▪️ *Корпус:*",
        'report_summary_work_type': "▪️ *Вид работ:*",
        'report_summary_date': "▪️ *Дата:*",
        'report_summary_people': "▪️ *Кол-во человек:*",
        'report_summary_volume': "▪️ *Выполненный объем:*",
        'report_summary_notes': "▪️ *Примечание:*",

        'report_creation_cancelled': "Создание отчета отменено",
        'report_saving_and_sending': "⏳ Сохраняю отчет и отправляю в группу...",
        'report_error_db_save': "❌ *Произошла ошибка при сохранении отчета в базу данных.*",
        'report_accepted_greeting': "✅ Ваш отчет принят.",
        
        'report_error_no_discipline': "❌ Ошибка: не удалось определить дисциплину для отчета.",
        'report_error_group_send': "❌ *Произошла ошибка при отправке отчета в группу.*",

        'roster_error_invalid_format': "❌ *Ошибка формата!* Пожалуйста, введите только числа, разделенные запятой (например: `5, 10`)",
        'roster_error_no_people': "❌ *Ошибка!* Вы не указали ни одного человека. Введите корректные данные.",

        'personnel_history_title': "История табелей",
'roster_for_period_title': "Табели по дисциплине «{discipline}» за {period}",
'no_rosters_for_period': "На выбранный период по дисциплине «{discipline}» табели не поданы.",
'pick_date_button': "Выбрать дату",
'all_disciplines_option': "Все дисциплины",
'history_prompt_date': "📅 *Введите дату (ДД.ММ.ГГГГ)* или диапазон дат через запятую (например, `01.07.2025, 07.07.2025`):",
'all_time_button': "Все время",

'report_menu_summary_title': "Общая сводка ({period})",
'total_brigades_in_system': "Всего бригад в системе:",
'brigades_in_discipline': "Бригад в дисциплине:",
'summary_for_your_brigade': "Сводка по вашей бригаде ({period})",
'reports_for_period': "Отчётов за период:",
'reports_approved': "✅ Согласовано:",
'reports_rejected': "❌ Отклонено:",
'reports_pending': "⏳ Ожидает:",
'select_report_detail': "Выберите детализацию отчёта:",
'all_time_button': "Все время",
'foreman_performance_button': "📊 Моя выработка",
'personnel_status_button': "👥 Статус персонала",
'back_to_main_menu_button': "🏠 В главное меню",
'report_overview_button': "📊 Общий обзор (график)",
'problem_brigades_button': "⚠️ Проблемные бригады",
'historical_overview_button': "📅 Исторический обзор",
'export_excel_button': "📤 Экспорт в Excel",
'delete_report_button': "🗑️ Удалить отчет",

'problem_brigades_title': "Проблемные бригады: {discipline}",
'problem_brigades_no_report_header': "🔴 Не сдали отчет сегодня:",
'problem_brigades_low_performance_header': "🟠 Низкая выработка (в среднем):",
'problem_brigades_no_issues': "✅ По дисциплине «{discipline}» проблемных бригад не найдено!",
'problem_brigades_avg_output_label': "Выработка",

'low_performance_brigade_count': "📉 Бригад с низкой выработкой: *{count}*",

'hr_menu_button': "👥 Людские ресурсы",
'hr_menu_title': "Меню «Людские ресурсы»",
'hr_menu_status_button': "📊 Статус персонала на сегодня",
'hr_menu_history_button': "🗓️ История табелей",
'detail_by_discipline_button': "Детально по «{discipline}»",

'hr_summary_title': "👥 Общая сводка по персоналу на сегодня",
'total_people_today': "▪️ Всего заявлено сегодня: *{total}* чел.",
'no_rosters_today': "На сегодня табели еще не поданы.",
'roster_details_by_brigade_title': "👥 Детализация по «{discipline}» за {period}",

'hr_discipline_select_prompt': "Выберите дисциплину для просмотра детализации:",
'hr_report_title': "Детализация по «{discipline}» за {date}",
'hr_report_summary': "▪️ Заявлено: *{total_people}* чел. ▪️ Сдали табель: *{brigade_count}* бригад",

    },
    'en': {
        # --- General ---
        'language_prompt': "Please select your language:",
        'language_changed': "✅ Language changed to English.",
        'back_button': "◀️ Back",
        'cancel_button': "❌ Cancel",
        'confirm_button': "✅ Confirm",
        'error_generic': "❌ An error occurred.",
        'unauthorized_action': "⛔️ You do not have permission to perform this action.",
        'data_not_found_error': "An error occurred, data not found. Please try again.",
        'loading_please_wait': "⏳ Please wait...",
        'action_cancelled': "Action cancelled.",
        'page_of': "Page {page} of {total_pages}",
        'yes_button': "✅ Yes",
        'no_button': "❌ No",
        'skip_button': "⏩ Skip",

        # show_profile
        'level_field': "▪️ Level:",
        'all_disciplines': "All",
        'error_unauthorized': "❌ Could not determine your role. Please try to authorize again.",

        'auth_role_approved_user': "🎉 Your role «{role}» has been confirmed!",


        # --- Main Menu ---
        'main_menu_title': "🏠 Main Menu",
        'submit_roster_button': "📋 Submit Roster for Today",
        'form_report_button': "📝 Create Report",
        'view_reports_button': "📊 View Reports",
        'profile_button': "👤 Profile",
        'auth_button': "🔐 Authorize",
        'manage_button': "⚙️ Management",
        'reports_group_button': "➡️ Go to reports group",
        'roster_summary_today': "\n\n📋 *Roster for today:*",
        'roster_composition': "▪️ *Composition:* {details}",
        'total_declared': "▪️ *Total declared:* {total} people",
        'completion_status': "\n\n📊 *Completion Status:*",
        'assigned_in_reports': "▪️ Assigned in reports: *{assigned}* people",
        'free_in_reserve': "▪️ Free in reserve: *{reserve}* people",

        # --- Auth & Profile ---
        'auth_prompt_role': "🔐 *Choose your future role:*",
        'auth_role_manager': "Manager",
        'auth_role_foreman': "Foreman",
        'auth_role_pto': "PTO",
        'auth_role_kiok': "QCC",
        'auth_prompt_name': "📝 *Enter your first and last name* (e.g., John Smith):",
        'auth_error_name': "❗ *Error: Please enter both first and last name, separated by a space.*\n\n📝 *Please try again:*",
        'auth_prompt_contact': "📞 *Great! Now press the button below to share your contact information.*",
        'auth_contact_button': "📞 Share my contact",
        'auth_prompt_manager_level': "⚙️ *Final step: choose your management level:*",
        'auth_manager_level1': "Level 1 (full access)",
        'auth_manager_level2': "Level 2 (by discipline)",
        'auth_prompt_discipline': "⚙️ *Final step: choose your discipline for the «{role}» role:*",
        'auth_prompt_discipline_manager': "⚙️ *...and your discipline for Level 2:*",
        'auth_pending_approval': "✅ *Data received.*\n\n*Your request has been sent for confirmation. Please wait...*",
        'auth_request_title': "🔐 *Registration Request*",
        'auth_request_rejected_user': "❌ *Your request for the «{role}» role was rejected.*",
        'auth_request_approved_admin': "✅ *The «{role}» role for {name} has been confirmed.*",
        'auth_request_rejected_admin': "❌ *The request for {name} was rejected.*",
        'profile_title': "👤 Your Profile:",
        'user_id_field': "▪️ UserID:",
        'phone_field': "▪️ Phone:",
        'username_field': "▪️ Username:",
        'role_field': "▪️ Role:",
        'brigade_field': "▪️ Brigade:",
        'discipline_field': "▪️ Discipline:",
        'level_field': "▪️ Level:",
        
        # --- Report Creation ---
        'report_step1_discipline': "📝 *Step 1: Which discipline is this report for?*",
        'report_step1_corpus': "📝 *Step 1: Select the building*",
        'report_step2_work_type': "📝 *Step 2: Select the work type for «{discipline}»*",
        'report_step3_people_count': "📝 *Step 3: Specify the number of people on site*",
        'report_step4_volume': "📝 *Step 4: Specify the completed volume in {unit}:*",
        'report_step4_volume_no_unit': "📝 *Step 4: Specify the completed volume:*",
        'report_step5_date': "📝 *Step 5: Select a date or enter it manually (DD.MM.YYYY)*",
        'report_step6_notes_prompt': "📝 *Step 6: Would you like to add a note?*\n_(drawing number, axes, issues, etc.)_",
        'report_add_note_button': "✅ Yes, add note",
        'report_final_confirmation_title': "📋 *Please check and confirm your report:*\n",
        'report_confirm_and_send_button': "✅ Confirm and send",
        'report_error_no_roster': "⚠️ *You must submit a roster for today first!* \n\nPlease use the button in the main menu to declare your brigade's composition.",
        'report_error_no_people': "❌ *Error!* You are trying to assign *{count}* people, but only *{reserve}* are left in the reserve.\n\nPlease enter a correct number.",
        'report_note_prompt': "✍️ Please enter your note in a single message:",
        'report_saved_and_sent': "✅ Report successfully saved and sent!",
        'report_saved_not_sent_error': "⚠️ *Report saved, but cannot be sent for approval!*\n\nReason: a group topic has not been configured for the «*{discipline}*» discipline.\n\nPlease ask an administrator to go to the correct topic and type the command:\n`/link_topic {discipline}`",
        'report_new_from_foreman': "📄 *New report from foreman: {foreman}* (ID: {report_id})\n",
        'report_status_pending': "*Status:* ⏳ Awaiting QCC approval",
        'report_status_approved': "*Status:* ✅ Approved by: {approver}",
        'report_status_rejected': "*Status:* ❌ Rejected by: {approver}",

        # --- Roster ---
        'roster_already_submitted': "⚠️ You have already submitted the roster for today.",
        'roster_prompt': "📋 *Submitting roster for {date}*\n\nPlease enter the number of people for each position, **separated by a comma**, strictly in the order shown.\nFor example, if you have 5 welders and 10 fitters, enter: `5, 10`\n\n**Your order is:**\n{roles_list}",
        'roster_confirm_prompt': "*Please check the data:*\n{summary}\n\n*Total: {total} people*",
        'roster_confirm_and_save_button': "✅ Correct, confirm",
        'roster_error_mismatch': "❌ *Error!* You entered {input_count} numbers, but {expected_count} were expected. Please enter a number for each position from the list.",
        'roster_saved_safely': "✅ *Roster for today successfully submitted!*\n\nYou have *{reserve}* people left in your reserve.",
        'roster_dangerous_save_warning': "‼️ *ATTENTION!* ‼️\n\nYou are trying to declare *{new_total}* people, but *{assigned}* are already assigned in today's reports.\n\nUpon confirmation, **all of your reports for today will be DELETED**, and you will have to reassign personnel.\n\nAre you sure you want to continue?",
        'roster_force_save_button': "✅ Yes, delete reports and save",
        'roster_force_saved_success': "✅ *Your reports for today have been deleted. The new roster has been submitted!*",

        'forward_button': "Forward ▶️",
        'today_button': "Today",
        'yesterday_button': "Yesterday",

        'report_error_no_work_types': "⚠️ *Error:* No work types found for the «{discipline}» discipline.",

        'report_error_invalid_number': "❗*Error:* Please enter the number of people as a single positive number (e.g., 5).",
        'report_error_invalid_volume': "❗*Error:* Please enter the completed volume as a single number (can be fractional).",
        'report_error_invalid_date': "❗*Error:* Invalid date format.\n\n📝 *Select a date with a button or enter it manually (DD.MM.YYYY)*",
        'report_summary_corpus': "▪️ *Building:*",
        'report_summary_work_type': "▪️ *Work Type:*",
        'report_summary_date': "▪️ *Date:*",
        'report_summary_people': "▪️ *People Count:*",
        'report_summary_volume': "▪️ *Completed Volume:*",
        'report_summary_notes': "▪️ *Note:*",
        'report_creation_cancelled': "Report creation cancelled",
        'report_saving_and_sending': "⏳ Saving report and sending to group...",
        'report_error_db_save': "❌ *An error occurred while saving the report to the database.*",
        'report_accepted_greeting': "✅ Your report has been accepted.",

        'report_error_no_discipline': "❌ Error: Could not determine the discipline for the report.",
        'report_error_group_send': "❌ *An error occurred while sending the report to the group.*",

        'roster_error_invalid_format': "❌ *Format error!* Please enter only numbers, separated by a comma (e.g., `5, 10`)",
        'roster_error_no_people': "❌ *Error!* You haven't specified any people. Please enter correct data.",

        'personnel_history_title': "Personnel Rosters History",
'roster_for_period_title': "Rosters for «{discipline}» discipline for {period}",
'no_rosters_for_period': "No rosters submitted for the «{discipline}» discipline for the selected period.",
'pick_date_button': "Select Date",
'all_disciplines_option': "All Disciplines",
'history_prompt_date': "📅 *Enter a date (DD.MM.YYYY)* or a date range separated by a comma (e.g., `01.07.2025, 07.07.2025`):",
'all_time_button': "All Time",

'report_menu_summary_title': "Overall Summary ({period})",
'total_brigades_in_system': "Total brigades in system:",
'brigades_in_discipline': "Brigades in discipline:",
'summary_for_your_brigade': "Summary for your brigade ({period})",
'reports_for_period': "Reports for the period:",
'reports_approved': "✅ Approved:",
'reports_rejected': "❌ Rejected:",
'reports_pending': "⏳ Pending:",
'select_report_detail': "Select report details:",
'all_time_button': "All Time",
'foreman_performance_button': "📊 My Performance",
'personnel_status_button': "👥 Personnel Status",
'back_to_main_menu_button': "🏠 Main Menu",
'report_overview_button': "📊 General Overview (chart)",
'problem_brigades_button': "⚠️ Problem Brigades",
'historical_overview_button': "📅 Historical Overview",
'export_excel_button': "📤 Export to Excel",
'delete_report_button': "🗑️ Delete Report",

'problem_brigades_title': "Problem Brigades: {discipline}",
'problem_brigades_no_report_header': "🔴 Did not submit a report today:",
'problem_brigades_low_performance_header': "🟠 Low Performance (on average):",
'problem_brigades_no_issues': "✅ No problem brigades found for «{discipline}» discipline!",
'problem_brigades_avg_output_label': "Performance",

'low_performance_brigade_count': "📉 Brigades with low performance: *{count}*",

'hr_menu_button': "👥 Human Resources",
'hr_menu_title': "Human Resources Menu",
'hr_menu_status_button': "📊 Personnel Status for Today",
'hr_menu_history_button': "🗓️ Roster History",
'detail_by_discipline_button': "Details for «{discipline}»",

'hr_summary_title': "👥 Overall Personnel Summary for Today",
'total_people_today': "▪️ Total declared today: *{total}* people",
'no_rosters_today': "No rosters have been submitted for today yet.",
'roster_details_by_brigade_title': "👥 Details for «{discipline}» for {period}",

'hr_discipline_select_prompt': "Select a discipline to view details:",
'hr_report_title': "Details for «{discipline}» for {date}",
'hr_report_summary': "▪️ Declared: *{total_people}* people ▪️ Rosters submitted: *{brigade_count}* brigades",

    },
    'uz': {
        # --- Umumiy ---
        'language_prompt': "Iltimos, tilingizni tanlang:",
        'language_changed': "✅ Til O'zbekchaga o'zgartirildi.",
        'back_button': "◀️ Orqaga",
        'cancel_button': "❌ Bekor qilish",
        'confirm_button': "✅ Tasdiqlash",
        'error_generic': "❌ Xatolik yuz berdi.",
        'unauthorized_action': "⛔️ Bu amalni bajarish uchun sizda ruxsat yo'q.",
        'data_not_found_error': "Xatolik yuz berdi, ma'lumotlar topilmadi. Iltimos, qaytadan urining.",
        'loading_please_wait': "⏳ Iltimos, kuting...",
        'action_cancelled': "Amal bekor qilindi.",
        'page_of': "{total_pages} dan {page}-sahifa",
        'yes_button': "✅ Ha",
        'no_button': "❌ Yo'q",
        'skip_button': "⏩ O'tkazib yuborish",

        # show_profile
        'level_field': "▪️ Daraja:",
        'all_disciplines': "Barchasi",
        'error_unauthorized': "❌ Rolingizni aniqlab boʻlmadi. Iltimos, qaytadan avtorizatsiyadan oʻting.",

        'auth_role_approved_user': "🎉 Sizning «{role}» rolingiz tasdiqlandi!",

        # --- Asosiy Menyu ---
        'main_menu_title': "🏠 Asosiy menyu",
        'submit_roster_button': "📋 Bugungi tabelni yuborish",
        'form_report_button': "📝 Hisobot yaratish",
        'view_reports_button': "📊 Hisobotlarni ko'rish",
        'profile_button': "👤 Profil",
        'auth_button': "🔐 Avtorizatsiya",
        'manage_button': "⚙️ Boshqaruv",
        'reports_group_button': "➡️ Hisobotlar guruhiga o'tish",
        'roster_summary_today': "\n\n📋 *Bugungi tabel:*",
        'roster_composition': "▪️ *Tarkib:* {details}",
        'total_declared': "▪️ *Jami arizada:* {total} kishi",
        'completion_status': "\n\n📊 *Bajarilish holati:*",
        'assigned_in_reports': "▪️ Hisobotlarda band: *{assigned}* kishi",
        'free_in_reserve': "▪️ Rezervda bo'sh: *{reserve}* kishi",

        # --- Avtorizatsiya & Profil ---
        'auth_prompt_role': "🔐 *Kelajakdagi rolingizni tanlang:*",
        'auth_role_manager': "Rahbar",
        'auth_role_foreman': "Brigadir",
        'auth_role_pto': "ITB (PTO)",
        'auth_role_kiok': "SIK (QCC)",
        'auth_prompt_name': "📝 *Ism va familiyangizni kiriting* (masalan: Alisher Usmonov):",
        'auth_error_name': "❗ *Xato: Iltimos, ism va familiyani bo'sh joy bilan ajratib kiriting.*\n\n📝 *Iltimos, qaytadan kiriting:*",
        'auth_prompt_contact': "📞 *Ajoyib! Endi kontaktingizni yuborish uchun quyidagi tugmani bosing.*",
        'auth_contact_button': "📞 Kontaktimni yuborish",
        'auth_prompt_manager_level': "⚙️ *Oxirgi qadam: boshqaruv darajangizni tanlang:*",
        'auth_manager_level1': "1-daraja (to'liq kirish)",
        'auth_manager_level2': "2-daraja (yo'nalish bo'yicha)",
        'auth_prompt_discipline': "⚙️ *Oxirgi qadam: «{role}» roli uchun yo'nalishingizni tanlang:*",
        'auth_prompt_discipline_manager': "⚙️ *...va 2-daraja uchun yo'nalishingizni tanlang:*",
        'auth_pending_approval': "✅ *Ma'lumotlar qabul qilindi.*\n\n*Sizning so'rovingiz tasdiqlash uchun yuborildi. Iltimos, kuting...*",
        'auth_request_title': "🔐 *Ro'yxatdan o'tish so'rovi*",
        'auth_request_rejected_user': "❌ *Sizning «{role}» roli uchun so'rovingiz rad etildi.*",
        'auth_request_approved_admin': "✅ *{name} uchun «{role}» roli tasdiqlandi.*",
        'auth_request_rejected_admin': "❌ *{name} uchun so'rov rad etildi.*",
        'profile_title': "👤 Sizning profilingiz:",
        'user_id_field': "▪️ UserID:",
        'phone_field': "▪️ Telefon:",
        'username_field': "▪️ Username:",
        'role_field': "▪️ Rol:",
        'brigade_field': "▪️ Brigada:",
        'discipline_field': "▪️ Yo'nalish:",
        'level_field': "▪️ Daraja:",

        # --- Hisobot Yaratish ---
        'report_step1_discipline': "📝 *1-qadam: Hisobot qaysi yo'nalish uchun yaratilmoqda?*",
        'report_step1_corpus': "📝 *1-qadam: Korpusni tanlang*",
        'report_step2_work_type': "📝 *2-qadam: «{discipline}» uchun ish turini tanlang*",
        'report_step3_people_count': "📝 *3-qadam: Ob'ektdagi odamlar sonini kiriting*",
        'report_step4_volume': "📝 *4-qadam: Bajarilgan hajmni {unit}da kiriting:*",
        'report_step4_volume_no_unit': "📝 *4-qadam: Bajarilgan hajmni kiriting:*",
        'report_step5_date': "📝 *5-qadam: Sanani tanlang yoki qo'lda kiriting (KK.OO.YYYY)*",
        'report_step6_notes_prompt': "📝 *6-qadam: Izoh qo'shishni xohlaysizmi?*\n_(chizma raqami, o'qlar, muammolar va hk.)_",
        'report_add_note_button': "✅ Ha, qo'shish",
        'report_final_confirmation_title': "📋 *Iltimos, hisobotingizni tekshiring va tasdiqlang:*\n",
        'report_confirm_and_send_button': "✅ Tasdiqlash va yuborish",
        'report_error_no_roster': "⚠️ *Avval bugungi tabelni topshirishingiz kerak!* \n\nBrigadangiz tarkibini e'lon qilish uchun asosiy menyudagi tugmadan foydalaning.",
        'report_error_no_people': "❌ *Xato!* Siz *{count}* kishini jalb qilmoqchisiz, lekin rezervda faqat *{reserve}* kishi qolgan.\n\nTo'g'ri raqamni kiriting.",
        'report_note_prompt': "✍️ Izohingizni bitta xabarda kiriting:",
        'report_saved_and_sent': "✅ Hisobot muvaffaqiyatli saqlandi va yuborildi!",
        'report_saved_not_sent_error': "⚠️ *Hisobot saqlandi, lekin kelishuvga yuborib bo'lmadi!*\n\nSabab: «*{discipline}*» yo'nalishi uchun guruhda mavzu sozlanmagan.\n\nAdministratorga kerakli mavzuga kirib, buyruqni yozishini so'rang:\n`/link_topic {discipline}`",
        'report_new_from_foreman': "📄 *Brigadirdan yangi hisobot: {foreman}* (ID: {report_id})\n",
        'report_status_pending': "*Holat:* ⏳ SIK (QCC) kelishuvi kutilmoqda",
        'report_status_approved': "*Holat:* ✅ Kelishildi: {approver}",
        'report_status_rejected': "*Holat:* ❌ Rad etildi: {approver}",

        # --- Tabel ---
        'roster_already_submitted': "⚠️ Siz bugungi tabelni allaqachon topshirgansiz.",
        'roster_prompt': "📋 *{date} uchun tabel topshirish*\n\nHar bir lavozim uchun odamlar sonini ko'rsatilgan tartibda, **vergul bilan ajratib** kiriting.\nMasalan, 5 ta payvandchi va 10 ta montajchi bo'lsa, kiriting: `5, 10`\n\n**Sizning tartibingiz:**\n{roles_list}",
        'roster_confirm_prompt': "*Ma'lumotlarni tekshiring:*\n{summary}\n\n*Jami: {total} kishi*",
        'roster_confirm_and_save_button': "✅ To'g'ri, tasdiqlayman",
        'roster_error_mismatch': "❌ *Xato!* Siz {input_count} ta raqam kiritdingiz, lekin {expected_count} ta kutilgan edi. Iltimos, ro'yxatdagi har bir lavozim uchun son kiriting.",
        'roster_saved_safely': "✅ *Bugungi tabel muvaffaqiyatli qabul qilindi!*\n\nSizning reservingizda *{reserve}* kishi qoldi.",
        'roster_dangerous_save_warning': "‼️ *DIQQAT!* ‼️\n\nSiz *{new_total}* kishini e'lon qilmoqchisiz, lekin bugungi hisobotlarda allaqachon *{assigned}* kishi band.\n\nTasdiqlaganingizdan so'ng, **bugungi barcha hisobotlaringiz O'CHIRILADI** va xodimlarni qaytadan taqsimlashingiz kerak bo'ladi.\n\nDavom etishni xohlaysizmi?",
        'roster_force_save_button': "✅ Ha, hisobotlarni o'chirib, saqlash",
        'roster_force_saved_success': "✅ *Bugungi hisobotlaringiz o'chirildi. Yangi tabel qabul qilindi!*",

        # Добавьте это в секцию 'uz'
        'forward_button': "Oldinga ▶️",
        'today_button': "Bugun",
        'yesterday_button': "Kecha",

        'report_error_no_work_types': "⚠️ *Xato:* «{discipline}» yo'nalishi uchun ish turlari topilmadi.",

        'report_error_invalid_number': "❗*Xato:* Iltimos, odamlar sonini bitta musbat son bilan kiriting (masalan: 5).",
        'report_error_invalid_volume': "❗*Xato:* Iltimos, bajarilgan hajmni bitta son bilan kiriting (kasr bo'lishi mumkin).",
        'report_error_invalid_date': "❗*Xato:* Sana formati noto'g'ri.\n\n📝 *Tugma yordamida sanani tanlang yoki qo'lda kiriting (KK.OO.YYYY)*",
        'report_summary_corpus': "▪️ *Korpus:*",
        'report_summary_work_type': "▪️ *Ish turi:*",
        'report_summary_date': "▪️ *Sana:*",
        'report_summary_people': "▪️ *Odamlar soni:*",
        'report_summary_volume': "▪️ *Bajarilgan hajm:*",
        'report_summary_notes': "▪️ *Izoh:*",

        'report_creation_cancelled': "Hisobot yaratish bekor qilindi",
        'report_saving_and_sending': "⏳ Hisobot saqlanmoqda va guruhga yuborilmoqda...",
        'report_error_db_save': "❌ *Hisobotni ma'lumotlar bazasiga saqlashda xatolik yuz berdi.*",
        'report_accepted_greeting': "✅ Sizning hisobotingiz qabul qilindi.",
        'report_error_no_discipline': "❌ Xato: Hisobot uchun yo'nalishni aniqlab bo'lmadi.",
        'report_error_group_send': "❌ *Hisobotni guruhga yuborishda xatolik yuz berdi.*",

        'roster_error_invalid_format': "❌ *Format xatosi!* Iltimos, faqat vergul bilan ajratilgan raqamlarni kiriting (masalan: `5, 10`)",
        'roster_error_no_people': "❌ *Xato!* Siz birorta ham odam ko'rsatmadingiz. To'g'ri ma'lumotlarni kiriting.",

        'personnel_history_title': "Tabel tarixi",
'roster_for_period_title': "«{discipline}» yo'nalishi bo'yicha {period} uchun tabel",
'no_rosters_for_period': "Tanlangan davr uchun «{discipline}» yo'nalishi bo'yicha tabellar topshirilmagan.",
'pick_date_button': "Sanani tanlash",
'all_disciplines_option': "Barcha yo'nalishlar",
'history_prompt_date': "📅 *Sana kiriting (KK.OO.YYYY)* yoki vergul bilan ajratilgan sana oralig'ini kiriting (masalan, `01.07.2025, 07.07.2025`):",
'all_time_button': "Butun vaqt",

'report_menu_summary_title': "Umumiy hisobot ({period})",
'total_brigades_in_system': "Tizimdagi jami brigadalar:",
'brigades_in_discipline': "Yo'nalishdagi brigadalar:",
'summary_for_your_brigade': "Sizning brigadangiz bo'yicha hisobot ({period})",
'reports_for_period': "Davr uchun hisobotlar:",
'reports_approved': "✅ Tasdiqlangan:",
'reports_rejected': "❌ Rad etilgan:",
'reports_pending': "⏳ Kutilmoqda:",
'select_report_detail': "Hisobot tafsilotlarini tanlang:",
'all_time_button': "Butun vaqt",
'foreman_performance_button': "📊 Mening samaradorligim",
'personnel_status_button': "👥 Xodimlar holati",
'back_to_main_menu_button': "🏠 Asosiy menyuga",
'report_overview_button': "📊 Umumiy ko'rinish (grafik)",
'problem_brigades_button': "⚠️ Muammoli brigadalar",
'historical_overview_button': "📅 Tarixiy ko'rinish",
'export_excel_button': "📤 Excelga eksport",
'delete_report_button': "🗑️ Hisobotni o'chirish",

'problem_brigades_title': "Muammoli brigadalar: {discipline}",
'problem_brigades_no_report_header': "🔴 Bugun hisobot topshirmaganlar:",
'problem_brigades_low_performance_header': "🟠 Past samaradorlik (o'rtacha):",
'problem_brigades_no_issues': "✅ «{discipline}» yo'nalishi bo'yicha muammoli brigadalar topilmadi!",
'problem_brigades_avg_output_label': "Samaradorlik",

'low_performance_brigade_count': "📉 Samaradorligi past brigadalar soni: *{count}*",

'hr_menu_button': "👥 Xodimlar bo'limi",
'hr_menu_title': "Xodimlar bo'limi menyusi",
'hr_menu_status_button': "📊 Bugungi xodimlar holati",
'hr_menu_history_button': "🗓️ Tabel tarixi",
'detail_by_discipline_button': "«{discipline}» bo'yicha batafsil",

'hr_summary_title': "👥 Bugungi xodimlar bo'yicha umumiy ma'lumot",
'total_people_today': "▪️ Bugun jami e'lon qilingan: *{total}* kishi",
'no_rosters_today': "Bugungi kun uchun hali tabel topshirilmagan.",
'roster_details_by_brigade_title': "👥 {period} uchun «{discipline}» bo'yicha tafsilotlar",

'hr_discipline_select_prompt': "Tafsilotlarni ko'rish uchun yo'nalishni tanlang:",
'hr_report_title': "{date} uchun «{discipline}» bo'yicha tafsilotlar",
'hr_report_summary': "▪️ E'lon qilingan: *{total_people}* kishi ▪️ Tabel topshirgan: *{brigade_count}* brigada",

    }
}

DEFAULT_LANGUAGE = 'ru'

# Вставьте этот код в конец файла localization.py, заменив старую версию

# Словарь для перевода данных из БД (названия работ, дисциплин и т.д.)
DATA_TRANSLATIONS = {
    # --- ДИСЦИПЛИНЫ ---
    'Механомонтаж': {'en': 'Mechanical Installation', 'uz': 'Mexanik montaj'},
    'Бетонные работы': {'en': 'Concrete Works', 'uz': 'Beton ishlari'},
    'КИПиА': {'en': 'Instrumentation & Automation', 'uz': 'O\'lchov asboblari va avtomatika'},
    'Металлоконструкция': {'en': 'Steel Structures', 'uz': 'Metall konstruksiyalar'},
    'Отделочные работы': {'en': 'Finishing Works', 'uz': 'Pardozlash ishlari'},
    'Трубопровод': {'en': 'Piping', 'uz': 'Quvurlar'},
    'Земляные работы': {'en': 'Earthworks', 'uz': 'Yer ishlari'},

    # --- ВИДЫ РАБОТ ---
    'Монтаж лестниц, площадок, стоек и др. Малотоннажных конструкций на сварке': {'en': 'Installation of stairs, platforms, racks and other light-duty welded structures', 'uz': 'Zinapoyalar, maydonchalar, ustunlar va boshqa yengil payvandlangan konstruksiyalarni montaj qilish'},
    'Монтаж металлоконструкций': {'en': 'Installation of steel structures', 'uz': 'Metall konstruksiyalarni montaj qilish'},
    'Изготовление металлоконструкций': {'en': 'Fabrication of steel structures', 'uz': 'Metall konstruksiyalarni tayyorlash'},
    'Изготовление мелких металлоконструкций на стройплощадке': {'en': 'Fabrication of small steel structures on site', 'uz': 'Qurilish maydonchasida mayda metall konstruksiyalarni tayyorlash'},
    'Монтаж опор для трубопровода': {'en': 'Installation of pipe supports', 'uz': 'Quvur uchun tayanchlarni montaj qilish'},
    'Сварка стыков технологических трубопроводов': {'en': 'Welding of process pipeline joints', 'uz': 'Texnologik quvur choklarini payvandlash'},
    'Монтаж ЗРА': {'en': 'Installation of shut-off and control valves', 'uz': 'To\'xtatuvchi va rostlovchi armatura (ZRA) montaji'},
    'Гидравлическое испытание трубопроводов': {'en': 'Hydraulic testing of pipelines', 'uz': 'Quvurlarni gidravlik sinovdan o\'tkazish'},
    'Монтаж парафланцевого соединения': {'en': 'Installation of a pair of flange connections', 'uz': 'Paraflanesli birikmalarni montaj qilish'},
    'Монтаж внутренних специализированных конструкций оборудования': {'en': 'Installation of internal specialized equipment structures', 'uz': 'Uskunaning ichki ixtisoslashtirilgan konstruksiyalarini montaj qilish'},
    'Футеровка стен тепловых агрегатов плитными материалами': {'en': 'Lining of thermal unit walls with slab materials', 'uz': 'Issiqlik agregatlari devorlarini plita materiallari bilan qoplash'},
    'Устройство бетонной подливки': {'en': 'Concrete grouting', 'uz': 'Beton quyish (podlivka)'},
    'Монтаж агрегатов насосных центробежных': {'en': 'Installation of centrifugal pump units', 'uz': 'Markazdan qochma nasos agregatlarini montaj qilish'},
    'Конвейер ленточный стационарный': {'en': 'Stationary belt conveyor', 'uz': 'Statsionar lenta konveyeri'},
    'Флотационная машина: монтаж': {'en': 'Flotation machine: installation', 'uz': 'Flotatsion mashina: montaj'},
    'Монтаж стенки резервуара (рулонных заготовок)': {'en': 'Installation of tank wall (from rolled plates)', 'uz': 'Rezervuar devorini montaj qilish (rulonli qismlardan)'},
    'Монтаж днища из рулонных заготовок для резервуаров': {'en': 'Installation of tank bottom from rolled plates', 'uz': 'Rezervuarlar uchun rulonli qismlardan tubini montaj qilish'},
    'Монтаж кровли из рулонных заготовок для резервуаров': {'en': 'Installation of tank roof from rolled plates', 'uz': 'Rezervuarlar uchun rulonli qismlardan tomini montaj qilish'},
    'Мельница шаровая мокрого помола: барабан диаметром свыше 7000 мм, длина свыше 13000 мм': {'en': 'Wet grinding ball mill: drum diameter over 7000 mm, length over 13000 mm', 'uz': 'Ho\'l maydalash sharli tegirmoni: baraban diametri 7000 mm dan ortiq, uzunligi 13000 mm dan ortiq'},
    'Дробилка конусная для крупного дробления, ширина загрузочного/разгрузочного отверстия, мм 1500/200': {'en': 'Cone crusher for coarse crushing, loading/unloading opening width, mm 1500/200', 'uz': 'Yirik maydalash uchun konusli maydalagich, yuklash/tushirish teshigi kengligi, mm 1500/200'},
    'МОНТАЖ СБОРНЫХ ЖЕЛЕЗОБЕТОННЫХ КОНСТРУКТИВНЫХ ЭЛЕМЕНТОВ ЗДАНИЙ И СООРУЖЕНИЙ: БАЛОК': {'en': 'INSTALLATION OF PRECAST CONCRETE ELEMENTS: BEAMS', 'uz': 'YIG\'MA TEMIR-BETON ELEMENTLARNI MONTAJ QILISH: TO\'SINLAR'},
    'УСТАНОВКА СБОРНЫХ ЖЕЛЕЗОБЕТОННЫХ ФУНДАМЕНТОВ': {'en': 'INSTALLATION OF PRECAST CONCRETE FOUNDATIONS', 'uz': 'YIG\'MA TEMIR-BETON POYDEVORLARNI O\'RNATISH'},
    'МОНОЛИТНЫЕ ЖЕЛЕЗОБЕТОННЫЕ КОНСТРУКЦИИ': {'en': 'MONOLITHIC REINFORCED CONCRETE STRUCTURES', 'uz': 'MONOLIT TEMIR-BETON KONSTRUKSIYALARI'},
    'МОНТАЖ СБОРНЫХ ЖЕЛЕЗОБЕТОННЫХ КОЛОДЦЕВ': {'en': 'INSTALLATION OF PRECAST CONCRETE MANHOLES', 'uz': 'YIG\'MA TEMIR-BETON QUDUQLARNI MONTAJ QILISH'},
    'УСТРОЙСТВО МОНОЛИТНЫХ ЖЕЛЕЗОБЕТОННЫХ КОЛОДЦЕВ': {'en': 'CONSTRUCTION OF MONOLITHIC CONCRETE MANHOLES', 'uz': 'MONOLIT TEMIR-BETON QUDUQLARNI QURISH'},
    'УСТРОЙСТВО ЖЕЛЕЗОБЕТОННЫХ МОНОЛИТНЫХ ЛОТКОВ': {'en': 'CONSTRUCTION OF MONOLITHIC CONCRETE CHANNELS', 'uz': 'MONOLIT TEMIR-BETON LOTOKLARNI QURISH'},
    'НАСЕЧКА ЖЕЛЕЗОБЕТОННЫХ ФУНДАМЕНТОВ': {'en': 'SCARIFYING OF CONCRETE FOUNDATIONS', 'uz': 'TEMIR-BETON POYDEVORLARNI OYISH'},
    'УСТРОЙСТВО БЕТОННОЙ ПОДГОТОВКИ': {'en': 'CONCRETE BLINDING INSTALLATION', 'uz': 'BETON TAYYORGARLIGINI QURISH'},
    'МОНТАЖ И ДЕМОНТАЖ ОПАЛУБКИ': {'en': 'FORMWORK ASSEMBLY AND DISMANTLING', 'uz': 'OPALUBKANI MONTAJ VA DEMONTAJ QILISH'},
    'УСТРОЙСТВО ЖЕЛЕЗОБЕТОННЫХ ФУНДАМЕНТОВ': {'en': 'CONSTRUCTION OF REINFORCED CONCRETE FOUNDATIONS', 'uz': 'TEMIR-BETON POYDEVORLARNI QURISH'},
    'УСТРОЙСТВО БЕТОННЫХ ФУНДАМЕНТОВ ОБЩЕГО НАЗНАЧЕНИЯ ОБЪЕМОМ ДО 1 М3': {'en': 'CONSTRUCTION OF GENERAL-PURPOSE CONCRETE FOUNDATIONS UP TO 1 M3', 'uz': '1 M3 GACHA HAJMDAGI UMUMIY MAQSADLI BETON POYDEVORLARNI QURISH'},
    'ВЯЗКА АРМАТУРНЫХ СТЕРЖНЕЙ ПОД ФУНДАМЕНТЫ, ПОЛЫ И ОТМОСТКИ': {'en': 'TYING OF REINFORCEMENT BARS FOR FOUNDATIONS, FLOORS AND BLIND AREAS', 'uz': 'POYDEVORLAR, POLLAR VA OTMOSTKALAR UCHUN ARMATURA BOG\'LASH'},
    'ВЯЗКА АРМАТУРНЫХ СТЕРЖНЕЙ ПОД КОЛОННЫ, СТЕНЫ, БАЛКИ, РИГЕЛИ, ПЕРЕКРЫТИЯ': {'en': 'TYING OF REINFORCEMENT BARS FOR COLUMNS, WALLS, BEAMS, GIRDERS, SLABS', 'uz': 'USTUNLAR, DEVORLAR, TO\'SINLAR, RIGELLAR, PLITALAR UCHUN ARMATURA BOG\'LASH'},
    'ИЗГОТОВЛЕНИЕ АРМАТУРНЫХ СТЕРЖНЕЙ': {'en': 'FABRICATION OF REINFORCEMENT BARS', 'uz': 'ARMATURA STERJENLARINI TAYYORLASH'},
    'МОНТАЖ АНКЕРНЫХ БОЛТОВ': {'en': 'INSTALLATION OF ANCHOR BOLTS', 'uz': 'ANKER BOLTLARINI MONTAJ QILISH'},
    'УСТАНОВКА ЗАКЛАДНЫХ ДЕТАЛЕЙ ДО 4 КГ': {'en': 'INSTALLATION OF EMBEDDED PARTS UP TO 4 KG', 'uz': '4 KG GACHA BO\'LGAN O\'RNATMA DETALLARNI O\'RNATISH'},
    'УСТАНОВКА ЗАКЛАДНЫХ ДЕТАЛЕЙ СВЫШЕ 4 КГ': {'en': 'INSTALLATION OF EMBEDDED PARTS OVER 4 KG', 'uz': '4 KG DAN ORTIQ BO\'LGAN O\'RNATMA DETALLARNI O\'RNATISH'},
    'ПРИГОТОВЛЕНИЕ ТЯЖЕЛОГО БЕТОНА': {'en': 'PREPARATION OF HEAVYWEIGHT CONCRETE', 'uz': 'OG\'IR BETON TAYYORLASH'},
    'СВЕРЛЕНИЕ ОТВЕРСТИЙ В ЖЕЛЕЗОБЕТОННЫХ КОНСТРУКЦИЯХ': {'en': 'DRILLING HOLES IN REINFORCED CONCRETE STRUCTURES', 'uz': 'TEMIR-BETON KONSTRUKSIYALARDA TESHIKLAR OCHISH'},
    'УСТАНОВКА АНКЕРНЫХ БОЛТОВ: ХИМИЧЕСКИХ': {'en': 'INSTALLATION OF CHEMICAL ANCHOR BOLTS', 'uz': 'KIMYOVIY ANKER BOLTLARINI O\'RNATISH'},
    'УСТАНОВКА И ДЕМОНТАЖ ИНВЕНТАРНЫХ ЛЕСОВ': {'en': 'INSTALLATION AND DISMANTLING OF INVENTORY SCAFFOLDING', 'uz': 'INVENTAR HAVOZALARNI O\'RNATISH VA DEMONTAJ QILISH'},
    'УСТРОЙСТВО ПОЛОВ БЕТОННЫХ ТОЛЩИНОЙ ДО 20 СМ': {'en': 'CONSTRUCTION OF CONCRETE FLOORS UP TO 20 CM THICK', 'uz': 'QALINLIGI 20 SM GACHA BO\'LGAN BETON POLLARNI YOTQIZISH'},
    'АРМИРОВАНИЕ ПОДСТИЛАЮЩИХ СЛОЕВ И НАБЕТОНОК СЕТКОЙ ЗАВОДСКОГО ИЗГОТОВЛЕНИЯ': {'en': 'REINFORCEMENT OF SUB-LAYERS AND CONCRETE OVERLAYS WITH FACTORY-MADE MESH', 'uz': 'ZAVODDA TAYYORLANGAN TO\'R BILAN ASTAR QATLAMLARINI VA BETON QOPLAMALARNI ARMATURALASH'},
    'УСТАНОВКА ЖЕЛЕЗОБЕТОННЫХ ОГРАД ИЗ ПАНЕЛЕЙ : ПО БЕТОННЫМ СТОЛБАМ Ж/Б ПАНЕЛИ ДЛИНОЙ ДО 3 МЕТРОВ': {'en': 'INSTALLATION OF REINFORCED CONCRETE FENCES FROM PANELS: ON CONCRETE POSTS, RC PANELS UP TO 3 METERS LONG', 'uz': 'PANELDAN TEMIR-BETON TO\'SIQLARNI O\'RNATISH: BETON USTUNLARGA, UZUNLIGI 3 METRGACHA BO\'LGAN T/B PANELLAR'},
    'УСТРОЙСТВО ДЕФОРМАЦИОННЫХ ШВОВ С ПРИМЕНЕНИЕМ ГЕРМЕТИКА': {'en': 'CONSTRUCTION OF EXPANSION JOINTS USING SEALANT', 'uz': 'GERMETIK ISHLATIB DEFORMATSION CHOKLARNI QURISH'},
    'УСТРОЙСТВО ПРОКЛАДОЧНОЙ ГИДРОИЗОЛЯЦИИ ФУНДАМЕНТОВ РУЛОННЫМИ МАТЕРИАЛАМИ В ОДИН СЛОЙ НАСУХО': {'en': 'DRY-LAID SINGLE-LAYER ROLL-TYPE WATERPROOFING OF FOUNDATIONS', 'uz': 'POYDEVORLARNI BIR QAVATLI RULONLI MATERIALLAR BILAN QURUQ GIDROIZOLYATSIYA QILISH'},
    'ДЕМОНТАЖ ФУНДАМЕНТОВ ЖЕЛЕЗОБЕТОННЫХ': {'en': 'DISMANTLING OF REINFORCED CONCRETE FOUNDATIONS', 'uz': 'TEMIR-BETON POYDEVORLARNI DEMONTAJ QILISH'},
    'СВЕРЛЕНИЕ ОТВЕРСТИЙ В БЕТОННЫХ КОНСТРУКЦИЯХ ПЕРФОРАТОРОМ ГЛУБИНОЙ 200 ММ ДО Ø 80 ММ': {'en': 'DRILLING HOLES IN CONCRETE STRUCTURES WITH A HAMMER DRILL, DEPTH 200 MM, UP TO Ø 80 MM', 'uz': 'BETON KONSTRUKSIYALARDA PERFORATOR BILAN 200 MM CHUQURLIKDA, Ø 80 MM GACHA TESHIK OCHISH'},
    'ШТРОБЛЕНИЕ БЕТОННЫХ СТЕН, ПОЛОВ И ПОТОЛКОВ': {'en': 'CHASING OF CONCRETE WALLS, FLOORS, AND CEILINGS', 'uz': 'BETON DEVORLAR, POLLAR VA SHIFTLARNI SHTROBLASH'},
    'УСТРОЙСТВО ДОРОГ ИЗ СБОРНЫХ ЖЕЛЕЗОБЕТОННЫХ ПЛИТ': {'en': 'CONSTRUCTION OF ROADS FROM PRECAST CONCRETE SLABS', 'uz': 'YIG\'MA TEMIR-BETON PLITALARDAN YO\'LLAR QURISH'},
    'УСТРОЙСТВО ЖЕЛЕЗОБЕТОННЫХ СБОРНЫХ ЛОТКОВ': {'en': 'INSTALLATION OF PRECAST CONCRETE CHANNELS', 'uz': 'YIG\'MA TEMIR-BETON LOTOKLARNI O\'RNATISH'},
    'УПЛОТНЕНИЕ ГРУНТА ЩЕБНЕМ ТОЛЩ. 10 СМ': {'en': 'SOIL COMPACTION WITH CRUSHED STONE, 10 CM THICK', 'uz': '10 SM QALINLIKDA SHAG\'AL BILAN TUPROQNI ZICHLASH'},
    'УСТРОЙСТВО ПОДСТИЛАЮЩИХ СЛОЕВ ВРУЧНУЮ (ЩЕБЕНОЧНЫХ, ПЕСЧАННЫХ, ГРАВИЙНЫХ)': {'en': 'MANUAL INSTALLATION OF SUB-LAYERS (CRUSHED STONE, SAND, GRAVEL)', 'uz': 'QO\'LDA ASTAR QATLAMLARINI YOTQIZISH (SHAG\'AL, QUM, GRAVIY)'},
    'ПЛАНИРОВКА ПЛОЩАДЕЙ РУЧНЫМ СПОСОБОМ': {'en': 'MANUAL GRADING OF AREAS', 'uz': 'MAYLONLARNI QO\'LDA TEKISLASH'},
    'УСТРОЙСТВО ПОКРЫТИЙ ЩЕБЕНОЧНЫХ С ПРОПИТКОЙ БИТУМОМ': {'en': 'CONSTRUCTION OF CRUSHED STONE SURFACES WITH BITUMEN IMPREGNATION', 'uz': 'BITUM SHIMDIRILGAN SHAG\'AL QOPLAMALARINI QURISH'},
    'ПОСЕВ ГАЗОНОВ ВРУЧНУЮ С ПОДГОТОВКОЙ ПОЧВЫ': {'en': 'MANUAL LAWN SOWING WITH SOIL PREPARATION', 'uz': 'TUPROQNI TAYYORLAB QO\'LDA GAZON EKISH'},
    'ПОСАДКА ДЕРЕВЬЕВ С ПОДГОТОВКОЙ ПОСАДОЧНЫХ МЕСТ': {'en': 'PLANTING TREES WITH PREPARATION OF PLANTING PITS', 'uz': 'O\'Tqazish joylarini tayyorlab daraxt ekish'},
    'ОБРАТНАЯ ЗАСЫПКА С УПЛОТНЕНИЕМ ВРУЧНУЮ': {'en': 'MANUAL BACKFILLING WITH COMPACTION', 'uz': 'QO\'LDA ZICHLAB QAYTA TO\'LDIRISH'},
    'ДОРАБОТКА ГРУНТА ВРУЧНУЮ': {'en': 'MANUAL SOIL FINISHING', 'uz': 'TUPROQNI QO\'LDA YAKUNLASH'},
    'УСТАНОВКА ДВЕРНЫХ И ОКОННЫХ БЛОКОВ В СТЕНАХ': {'en': 'INSTALLATION OF DOOR AND WINDOW UNITS IN WALLS', 'uz': 'DEVORLARGA ESHIK VA OYNA BLOKLARINI O\'RNATISH'},
    'ШТУКАТУРКА СТЕН': {'en': 'WALL PLASTERING', 'uz': 'DEVORLARNI SUVOQLASH'},
    'ШТУКАТУРКА ПОТОЛКОВ': {'en': 'CEILING PLASTERING', 'uz': 'SHIFTLARNI SUVOQLASH'},
    'ШТУКАТУРКА ОТКОСОВ': {'en': 'PLASTERING OF SLOPES/REVEALS', 'uz': 'OTKOSLARNI SUVOQLASH'},
    'ШПАТЛЕВКА БЕТОННЫХ ПОВЕРХНОСТЕЙ СТЕН, КОЛОНН': {'en': 'PUTTYING OF CONCRETE SURFACES OF WALLS, COLUMNS', 'uz': 'DEVORLAR, USTUNLARNING BETON YUZALARINI SHPATLYOVKA QILISH'},
    'ШПАТЛЕВКА РИГЕЛЕЙ И ПОТОЛКОВ': {'en': 'PUTTYING OF GIRDERS AND CEILINGS', 'uz': 'RIGELLAR VA SHIFTLARNI SHPATLYOVKA QILISH'},
    'ОКРАСКА ВОДОЭМУЛЬСИОННЫМИ СОСТАВАМИ ПО ШТУКАТУРКЕ СТЕН ВЫСОКОКАЧЕСТВЕННАЯ': {'en': 'HIGH-QUALITY WALL PAINTING WITH WATER-BASED EMULSION OVER PLASTER', 'uz': 'DEVORLARNI SUV-EMULSIYALI BO\'YOQLAR BILAN YUQORI SIFATLI BO\'YASH'},
    'ОКРАСКА ВОДОЭМУЛЬСИОННЫМИ СОСТАВАМИ РИГЕЛЕЙ, ПОТОЛКОВ': {'en': 'PAINTING OF GIRDERS, CEILINGS WITH WATER-BASED EMULSION', 'uz': 'RIGELLAR, SHIFTLARNI SUV-EMULSIYALI BO\'YOQLAR BILAN BO\'YASH'},
    'ОБЛИЦОВКА СТЕН КЕРАМИЧЕСКОЙ ПЛИТКОЙ': {'en': 'WALL TILING WITH CERAMIC TILES', 'uz': 'DEVORLARNI KERAMIK PLITKA BILAN QOPLASH'},
    'ОКЛЕЙКА СТЕН МОЮЩИМИСЯ ОБОЯМИ': {'en': 'WALLPAPERING WITH WASHABLE WALLPAPER', 'uz': 'DEVORLARGA YUVILADIGAN GULQOG\'OZ YOPISHTIRISH'},
    'ОКРАСКА ПОВЕРХНОСТЕЙ СТЕН МАСЛЯННЫМИ СОСТАВАМИ ЗА ДВА РАЗА': {'en': 'PAINTING WALL SURFACES WITH OIL-BASED PAINT (TWO COATS)', 'uz': 'DEVOR YUZALARINI MOYLI BO\'YOQ BILAN IKKI MARTA BO\'YASH'},
    'ОКРАСКА ПОВЕРХНОСТЕЙ ПОТОЛКОВ МАСЛЯННЫМИ СОСТАВАМИ ЗА ДВА РАЗА': {'en': 'PAINTING CEILING SURFACES WITH OIL-BASED PAINT (TWO COATS)', 'uz': 'SHIF YUZALARINI MOYLI BO\'YOQ BILAN IKKI MARTA BO\'YASH'},
    'ОТДЕЛКА СТЕН ДЕКОРАТИВНЫМ ПОКРЫТИЕМ "ТРАВЕРТИН" С НАНЕСЕНИЕМ РИСУНКА И ПОЛИРОВКОЙ ПОВЕРХНОСТИ РУЧНЫМ СПОСОБОМ': {'en': 'WALL FINISHING WITH "TRAVERTINE" DECORATIVE COATING WITH PATTERN APPLICATION AND MANUAL SURFACE POLISHING', 'uz': 'DEVORLARNI "TRAVERTIN" DEKORATIV QOPLAMASI BILAN QO\'LDA NAQSH SOLIB VA JILO BERIB PARDOZLASH'},
    'УСТРОЙСТВО ПЕРЕГОРОДОК С ОДИНАРНЫМ МЕТАЛЛИЧЕСКИМ КАРКАСОМ И ДВУХСЛОЙНОЙ ОБШИВКОЙ ГИПСОКАРТОННЫМИ ПЛИТАМИ С ОБЕИХ СТОРОН С УТЕПЛЕНИЕМ': {'en': 'CONSTRUCTION OF PARTITIONS WITH SINGLE METAL FRAME AND DOUBLE-LAYER DRYWALL SHEATHING ON BOTH SIDES WITH INSULATION', 'uz': 'BIR QAVATLI METALL KARKASLI VA IKKI TOMONI IKKI QAVAT GIPSOKARTON PLITALAR BILAN QOPLANGAN VA ISITGICHLI TO\'SIQLAR QURISH'},
    'ОБЛИЦОВКА СТЕН ГИПСОКАРТОННЫМИ ЛИСТАМИ В ОДИН СЛОЙ С УТЕПЛЕНИЕМ': {'en': 'SINGLE-LAYER DRYWALL WALL LINING WITH INSULATION', 'uz': 'DEVORLARNI BIR QAVAT GIPSOKARTON PLITALAR BILAN ISITGICH BILAN QOPLASH'},
    'УСТРОЙСТВО ПОДВЕСНОГО ПОТОЛКА ГИПСОКАРТОННЫМИ ПЛИТАМИ ПО МЕТАЛЛИЧЕСКИМ НЕСУЩИМ КОНСТРУКЦИЯМ': {'en': 'DRYWALL SUSPENDED CEILING INSTALLATION ON METAL SUPPORTING STRUCTURES', 'uz': 'METALL KONSTRUKSIYALARGA GIPSOKARTON PLITALARDAN OSMA SHIFT QURISH'},
    'УСТРОЙСТВО ПОДВЕСНЫХ ПОТОЛКОВ ТИПА "АРМСТРОНГ"': {'en': '"ARMSTRONG" TYPE SUSPENDED CEILING INSTALLATION', 'uz': '"ARMSTRONG" TURIDAGI OSMA SHIFTLARNI QURISH'},
    'ОБЛИЦОВКА ФАСАДА ПАНЕЛЯМИ "АЛЮПАН" ИЛИ "АЛЮКОБОНД" С УСТРОЙСТВОМ КАРКАСА': {'en': 'FACADE CLADDING WITH "ALUPAN" OR "ALUCOBOND" PANELS WITH FRAME INSTALLATION', 'uz': '"ALUPAN" YOKI "ALUCOBOND" PANELLARI BILAN KARKAS O\'RNATIB FASADNI QOPLASH'},
    'УСТРОЙСТВО ПОКРЫТИЙ ПОЛОВ ИЗ КЕРАМИЧЕСКИХ ПЛИТОК': {'en': 'CERAMIC TILE FLOORING INSTALLATION', 'uz': 'KERAMIK PLITKALARDAN POL QOPLAMALARINI YOTQIZISH'},
    'УСТРОЙСТВО ПОКРЫТИЙ ПОЛОВ ИЗ ЛИНОЛЕУМА И КОВРОЛИНА С ПЛИНТУСОМ': {'en': 'LINOLEUM AND CARPET FLOORING INSTALLATION WITH SKIRTING BOARDS', 'uz': 'PLINTUS BILAN LINOLEUM VA KOVROLIN POL QOPLAMALARINI YOTQIZISH'},
    'УСТРОЙСТВО СТЯЖЕК ТОЛЩИНОЙ ДО 10 СМ': {'en': 'SCREED INSTALLATION UP TO 10 CM THICK', 'uz': '10 SM QALINLIKKACHA STYASHKA YOTQIZISH'},
    'УСТРОЙСТВО ПОКРЫТИЙ ПОЛОВ ИЗ ЛАМИНАТА': {'en': 'LAMINATE FLOORING INSTALLATION', 'uz': 'LAMINAT POL QOPLAMALARINI YOTQIZISH'},
    'УСТРОЙСТВО НАЛИВНЫХ ПОЛОВ': {'en': 'SELF-LEVELING FLOOR INSTALLATION', 'uz': 'QUYMA POLLARNI YOTQIZISH'},
    'УСТРОЙСТВО ПОКРЫТИЙ ИЗ МОЗАИЧНОЙ ПЛИТКИ ТОЛЩ. 25ММ': {'en': 'TERRAZZO TILE FLOORING INSTALLATION, 25MM THICK', 'uz': '25MM QALINLIKDAGI MOZAIK PLITKA QOPLAMALARINI YOTQIZISH'},
    'УСТРОЙСТВО ФАЛЬШПОЛА ТОЛЩ. 75 ММ': {'en': 'RAISED FLOOR INSTALLATION, 75MM THICK', 'uz': '75MM QALINLIKDAGI SOXTA POL YOTQIZISH'},
    'УСТРОЙСТВО СТЯЖКИ КРОВЛИ ТОЛЩ. 20 ММ': {'en': 'ROOF SCREED INSTALLATION, 20MM THICK', 'uz': '20MM QALINLIKDAGI TOM STYASHKASINI YOTQIZISH'},
    'УСТРОЙСТВО КРОВЕЛЬ СКАТНЫХ ИЗ НАПЛАВЛЯЕМЫХ МАТЕРИАЛОВ В ТРИ СЛОЯ': {'en': 'THREE-LAYER TORCH-ON MEMBRANE PITCHED ROOFING', 'uz': 'UCH QAVATLI YONALTIRILADIGAN MATERIALLARDAN NIYOHLI TOM YOPISH'},
    'КЛАДКА АРМИРОВАННЫХ СТЕН ИЗ КИРПИЧА': {'en': 'REINFORCED BRICK WALL MASONRY', 'uz': 'ARMATURALANGAN G\'ISHT DEVORLARNI QURISH'},
    'КЛАДКА ПЕРЕГОРОДОК ИЗ КИРПИЧА АРМИРОВАННЫХ ТОЛЩИНОЙ В 1/2 КИРПИЧА': {'en': 'REINFORCED 1/2-BRICK THICK PARTITION MASONRY', 'uz': '1/2 G\'ISHT QALINLIGIDA ARMATURALANGAN TO\'SIQLARNI QURISH'},
    'УСТРОЙСТВО ДЕРЕВЯННЫХ КАРКАСОВ КРОВЛИ': {'en': 'TIMBER ROOF FRAME CONSTRUCTION', 'uz': 'YOG\'OCH TOM KARKASLARINI QURISH'},
    'ГИДРОИЗОЛЯЦИЯ ОКЛЕЕЧНАЯ В ДВА СЛОЯ': {'en': 'TWO-LAYER MEMBRANE WATERPROOFING', 'uz': 'IKKI QAVATLI YOPISHTIRILADIGAN GIDROIZOLYATSIYA'},
    'ГИДРОИЗОЛЯЦИЯ ОБМАЗОЧНАЯ БИТУМНАЯ В ДВА СЛОЯ': {'en': 'TWO-COAT BITUMINOUS WATERPROOFING', 'uz': 'IKKI QAVATLI BITUMLI SURALADIGAN GIDROIZOLYATSIYA'},
    'ПРИГОТОВЛЕНИЕ ТЯЖЕЛЫХ ОТДЕЛОЧНЫХ РАСТВОРОВ': {'en': 'PREPARATION OF HEAVY FINISHING MORTARS', 'uz': 'OG\'IR PARDOSHLASH QORISHMALARINI TAYYORLASH'},
    'МОНТАЖ ПОКРЫТИЯ ИЗ ПРОФЛИСТА: КРОВЕЛЬНОГО': {'en': 'INSTALLATION OF PROFILED SHEET COVERING: ROOFING', 'uz': 'PROFLIST QOPLAMASINI MONTAJ QILISH: TOM UCHUN'},
    'МОНТАЖ ПОКРЫТИЯ ИЗ ПРОФЛИСТА: СТЕНОВОГО': {'en': 'INSTALLATION OF PROFILED SHEET COVERING: WALLING', 'uz': 'PROFLIST QOPLAMASINI MONTAJ QILISH: DEVOR UCHUN'},
    'МОНТАЖ МЕТАЛЛИЧЕСКИХ ВОРОТ И ДВЕРЕЙ': {'en': 'INSTALLATION OF METAL GATES AND DOORS', 'uz': 'METALL DARVOZA VA ESHIKLARNI MONTAJ QILISH'},
    'МОНТАЖ КОЛЮЧЕЙ ПРОВОЛОКИ': {'en': 'BARBED WIRE INSTALLATION', 'uz': 'TIKANLI SIMNI MONTAJ QILISH'},
    'УСТРОЙСТВО ОГРАЖДЕНИЙ: ИЗ МЕТАЛЛИЧЕСКИХ ПАНЕЛЕЙ ПО Ж/Б СТОЛБАМ': {'en': 'FENCE INSTALLATION: FROM METAL PANELS ON REINFORCED CONCRETE POSTS', 'uz': 'TO\'SIQLARNI O\'RNATISH: TEMIR-BETON USTUNLARGA METALL PANELLARNI'},
    'УСТРОЙСТВО ОГРАЖДЕНИЙ: ИЗ МЕТАЛЛИЧЕСКИХ ПАНЕЛЕЙ ПО МЕТАЛЛИЧЕСКИМ СТОЛБАМ': {'en': 'FENCE INSTALLATION: FROM METAL PANELS ON METAL POSTS', 'uz': 'TO\'SIQLARNI O\'RNATISH: METALL USTUNLARGA METALL PANELLARNI'},
    'УСТРОЙСТВО ОГРАЖДЕНИЙ: УСТАНОВКА ВОРОТ СЕТЧАТЫХ': {'en': 'FENCE INSTALLATION: MESH GATE INSTALLATION', 'uz': 'TO\'SIQLARNI O\'RNATISH: TO\'RLI DARVOZALARNI O\'RNATISH'},
    'УСТРОЙСТВО ОГРАЖДЕНИЙ: УСТАНОВКА КАЛИТОК СЕТЧАТЫХ': {'en': 'FENCE INSTALLATION: MESH WICKET GATE INSTALLATION', 'uz': 'TO\'SIQLARNI O\'RNATISH: TO\'RLI ESHIKCHALARNI O\'RNATISH'},
    'ИЗГОТОВЛЕНИЕ ПОЛОТЕН (ВОРОТ, КАЛИТОК) ОГРАЖДЕНИЙ': {'en': 'FABRICATION OF FENCE LEAVES (GATES, WICKETS)', 'uz': 'TO\'SIQLAR UCHUN POLOTNO (DARVOZA, ESHIKCHA) YASASH'},
    'УСТРОЙСТВО СЭНДВИЧ-ПАНЕЛЕЙ : СТЕНЫ': {'en': 'SANDWICH PANEL INSTALLATION: WALLS', 'uz': 'SENDVICH-PANELLARNI O\'RNATISH: DEVORLAR'},
    'УСТРОЙСТВО СЭНДВИЧ-ПАНЕЛЕЙ : КРОВЛИ': {'en': 'SANDWICH PANEL INSTALLATION: ROOFING', 'uz': 'SENDVICH-PANELLARNI O\'RNATISH: TOM'},
    'УСТРОЙСТВО МЕЛКИХ ПОКРЫТИЙ (ПАРАПЕТЫ, СВЕСЫ, ОБДЕЛКИ, ЖЕЛОБЫ И Т.Д ) ИЗ ЛИСТОВОЙ ОЦИНКОВАННОЙ СТАЛИ': {'en': 'INSTALLATION OF SMALL COVERINGS (PARAPETS, EAVES, TRIMS, GUTTERS, ETC.) FROM GALVANIZED STEEL SHEETS', 'uz': 'RUXLANGAN PO\'LATDAN MAYDA QOPLAMALARNI O\'RNATISH (PARAPETLAR, KORNIZLAR, BEZAKLAR, NOVLAR VA HK.)'},
    'ОБЛИЦОВКА СТЕН ДЕКОРАТИВНЫМИ ПЛАСТИКОВЫМИ И МДФ ПАНЕЛЯМИ С УСТРОЙСТВОМ С КАРКАСА БЕЗ ОТНОСА ОТ СТЕНЫ': {'en': 'WALL CLADDING WITH DECORATIVE PLASTIC AND MDF PANELS WITH FRAME INSTALLATION FLUSH TO THE WALL', 'uz': 'DEVORLARNI DEKORATIV PLASTIK VA MDF PANELLAR BILAN DEVORGA YOPISHTIRIB KARKAS O\'RNATISH'},
    'ОБЛИЦОВКА ПОТОЛКА ДЕКОРАТИВНЫМИ ПЛАСТИКОВЫМИ И МДФ ПАНЕЛЯМИ С УСТРОЙСТВОМ КАРКАСА БЕЗ ОТНОСА ОТ ПОТОЛКА': {'en': 'CEILING CLADDING WITH DECORATIVE PLASTIC AND MDF PANELS WITH FRAME INSTALLATION FLUSH TO THE CEILING', 'uz': 'SHIFTLARNI DEKORATIV PLASTIK VA MDF PANELLAR BILAN SHIFTGA YOPISHTIRIB KARKAS O\'RNATISH'},
    'УСТРОЙСТВО ПОДВЕСНЫХ ПОТОЛКОВ: РЕЕЧНЫХ АЛЮМИНИЕВЫХ И КАССЕТНЫХ': {'en': 'SUSPENDED CEILING INSTALLATION: ALUMINUM SLAT AND CASSETTE TYPES', 'uz': 'OSMA SHIFTLARNI O\'RNATISH: ALYUMINIY REYKALI VA KASSETALI'},
    'ОБЛИЦОВКА ФАСАДОВ КЕРАМОГРАНИТНЫМИ ПЛИТАМИ НА ЦЕМЕНТНОМ РАСТВОРЕ С ЗАТИРКОЙ ШВОВ': {'en': 'FACADE CLADDING WITH PORCELAIN TILES ON CEMENT MORTAR WITH GROUTING', 'uz': 'FASADLARNI SEMENT QORISHMASIGA KERAMOGRANIT PLITALAR BILAN CHOKLARINI TO\'LDIRIB QOPLASH'},
    'НАРУЖНАЯ ОБЛИЦОВКА ФАСАДОВ САЙДИНГОМ (КЕРАМОСАЙДИНГ, САЙДИНГ ИЗ ДРЕВЕСИНЫ)': {'en': 'EXTERIOR FACADE CLADDING WITH SIDING (CERAMIC SIDING, WOOD SIDING)', 'uz': 'FASADLARNI SAYDING BILAN TASHQI QOPLASH (KERAMOSAYDING, YOG\'OCH SAYDING)'},
    'НАВЕСКА ВОДОСТОЧНЫХ ТРУБ': {'en': 'INSTALLATION OF DOWNSPOUTS', 'uz': 'SUV OQAR QUvURLARNI O\'RNATISH'},
    'КЛАДКА СТЕН И ПЕРЕГОРОДОК ИЗ ЛЕГКОБЕТОННЫХ КАМНЕЙ, ГАЗОБЛОКОВ БЕЗ ОБЛИЦОВКИ': {'en': 'MASONRY OF WALLS AND PARTITIONS FROM LIGHTWEIGHT CONCRETE BLOCKS, AERATED CONCRETE BLOCKS WITHOUT CLADDING', 'uz': 'YENGIL BETON TOSHLARDAN, GAZOBLOKLARDAN QOPLAMASIZ DEVOR VA TO\'SIQLARNI QURISH'},
    'УСТРОЙСТВО ДЕФОРМАЦИОННЫХ ШВОВ С ПРИМЕНЕНИЕМ РЕЗИНОВЫХ ПРОКЛАДОК, ЦЕМЕНТНЫХ РАСТВОРОВ': {'en': 'CONSTRUCTION OF EXPANSION JOINTS USING RUBBER GASKETS, CEMENT MORTARS', 'uz': 'REZINA PROKLADKALAR, SEMENT QORISHMALARI BILAN DEFORMATSION CHOKLARNI QURISH'},
    'УСТРОЙСТВО ПОКРЫТИЙ ПОЛОВ ИЗ ДОСОК ПАРКЕТНЫХ (ДОЩАТЫХ, ИЗ БРУСКОВ)': {'en': 'INSTALLATION OF PARQUET (PLANK, BLOCK) FLOORING', 'uz': 'PARKET (TAXTALI, BRUSOKLI) POLLARNI YOTQIZISH'},
    'УСТАНОВКА ПОТОЛОЧНЫХ ПЛИНТУСОВ': {'en': 'CEILING SKIRTING/CORNICE INSTALLATION', 'uz': 'SHIF PLINTUSLARINI O\'RNATISH'},
    'УСТРОЙСТВО КАРКАСОВ ЗДАНИЙ ИЗ ТОНКОЛИСТОВОЙ СТАЛИ (ЛСТК) НА БОЛТОВЫХ СОЕДИНЕНИЯХ': {'en': 'CONSTRUCTION OF LIGHT GAUGE STEEL FRAMED (LGSF) BUILDINGS WITH BOLTED CONNECTIONS', 'uz': 'YUPQA LISTLI PO\'LATDAN (LSTK) BOLTLI BIRIKMALARDA BINO KARKASLARINI QURISH'},
    'УСТРОЙСТВО НАРУЖНОЙ ТЕПЛОИЗОЛЯЦИИ ЗДАНИЙ С ТОНКОЙ ШТУКАТУРКОЙ ПО УТЕПЛИТЕЛЮ ТОЛЩИНОЙ ПЛИТ ДО: 100 ММ': {'en': 'EXTERIOR THERMAL INSULATION OF BUILDINGS WITH THIN PLASTER OVER INSULATION BOARDS UP TO 100 MM THICK', 'uz': 'QALINLIGI 100 MM GACHA BO\'LGAN ISITGICH USTIDAN YUPQA SUVOKLI BINOLARNING TASHQI ISSIQLIK IZOLYATSIYASINI QURISH'},
    'МОНТАЖ ПЕРЕГОРОДОК ИЗ АЛЮМИНИЕВЫХ СПЛАВОВ СБОРНО-РАЗБОРНЫХ С ОСТЕКЛЕНИЕМ': {'en': 'INSTALLATION OF PREFABRICATED ALUMINUM ALLOY PARTITIONS WITH GLAZING', 'uz': 'OYNALI YIG\'MA-AJRALADIGAN ALYUMINIY QOTISHMALARIDAN TO\'SIQLARNI MONTAJ QILISH'},
    'УСТРОЙСТВО ПЕРЕГОРОДОК ИЗ МДФ-ПАНЕЛЕЙ, АЛЮМИНИЯ, ПВХ ПРОФИЛЕЙ': {'en': 'CONSTRUCTION OF PARTITIONS FROM MDF PANELS, ALUMINUM, PVC PROFILES', 'uz': 'MDF-PANELLAR, ALYUMINIY, PVX PROFILLARDAN TO\'SIQLARNI QURISH'},
    'ОКРАСКА ПОВЕРХНОСТЕЙ МЕТАЛЛИЧЕСКИХ ВРУЧНУЮ, ВКЛЮЧАЯ ПОДГОТОВКУ ПОВЕРХНОСТИ': {'en': 'MANUAL PAINTING OF METAL SURFACES, INCLUDING SURFACE PREPARATION', 'uz': 'METALL YUZALARNI QO\'LDA BO\'YASH, YUZANI TAYYORLASH BILAN BIRGA'},
    'УСТРОЙСТВО ПЛИНТУСОВ ПВХ НА ВИНТАХ САМОНАРЕЗАЮЩИХ': {'en': 'INSTALLATION OF PVC SKIRTING BOARDS WITH SELF-TAPPING SCREWS', 'uz': 'PVX PLINTUSLARNI O\'ZI KESADIGAN VINTLARGA O\'RNATISH'},
    'УСТАНОВКА ПОДОКОННЫХ ДОСОК ИЗ ПВХ': {'en': 'INSTALLATION OF PVC WINDOW SILLS', 'uz': 'PVX PODOKONNIKLARNI O\'RNATISH'},
    'УСТРОЙСТВО ДЕКОРАТИВНОГО ПОКРЫТИЯ ТИПА "OTTOCENTO"': {'en': '"OTTOCENTO" TYPE DECORATIVE COATING APPLICATION', 'uz': '"OTTOCENTO" TURIDAGI DEKORATIV QOPLAMANI QURISH'},
    'Монтаж импульсной трубки': {'en': 'Impulse tube installation', 'uz': 'Impuls trubkasini montaj qilish'},
    'Монтаж металлических штампованных лотков': {'en': 'Installation of stamped metal trays', 'uz': 'Shtamplangan metall lotoklarni montaj qilish'},
    'Прокладка кабеля по лоткам': {'en': 'Cable laying in trays', 'uz': 'Lotoklarda kabel yotqizish'},
    'Прокладка кабеля по траншее': {'en': 'Cable laying in trench', 'uz': 'Transheyada kabel yotqizish'},
    'Монтаж приборов': {'en': 'Instrument installation', 'uz': 'Asboblarni montaj qilish'},
    'Прокладка кабеля в блоках и коробах': {'en': 'Cable laying in blocks and ducts', 'uz': 'Blok va kanallarda kabel yotqizish'},
    'Заделка для кабеля': {'en': 'Cable sealing/termination', 'uz': 'Kabel uchun germetiklash'},
    'Присоединение': {'en': 'Connection', 'uz': 'Ulanish'},
    'Монтаж Коробки': {'en': 'Junction Box Installation', 'uz': 'Quti montaji'},
    'Монтаж Щита': {'en': 'Panel/Board Installation', 'uz': 'Shit montaji'},
    'Прочие работы (Устранение замечаний, Очистка территории, подсобничество и т.д.)': {'en': 'Other works (Punch list clearance, site cleaning, auxiliary work, etc.)', 'uz': 'Boshqa ishlar (Kamchiliklarni bartaraf etish, hududni tozalash, yordamchi ishlar va hk.)'}
}

def get_data_translation(original_text: str, lang_code: str = 'ru') -> str:
    """
    Ищет перевод для данных. Если перевода нет, возвращает оригинальный текст.
    """
    # Язык по умолчанию 'ru', для него перевод не нужен
    if lang_code == 'ru' or not original_text:
        return original_text
    
    # Убираем лишние пробелы с краев для надежного поиска в словаре
    cleaned_text = original_text.strip()
    
    # Ищем перевод в словаре. Если не находим, возвращаем исходный очищенный текст.
    return DATA_TRANSLATIONS.get(cleaned_text, {}).get(lang_code, cleaned_text)

def get_text(key: str, lang_code: str = DEFAULT_LANGUAGE) -> str:
    """
    Возвращает переведенную строку по ключу и коду языка.
    Если перевод не найден, возвращает ключ как заглушку.
    """
    if not lang_code:
        lang_code = DEFAULT_LANGUAGE
    # Возвращает перевод для нужного языка. Если язык не найден, использует язык по умолчанию.
    return TRANSLATIONS.get(lang_code, TRANSLATIONS[DEFAULT_LANGUAGE]).get(key, f"_{key}_")