# Файл: localization.py

# Словарь, где хранятся все переводы.
TRANSLATIONS = {
    'ru': {
        # --- Общие ---
        'language_prompt': "Пожалуйста, выберите язык:",
        'language_changed': "✅ Язык изменен на Русский.",
        'back_button': "◀️ Назад",
        'cancel_button': "❌ Отмена",
        'confirm_button': "✅ Подтвердить",
        'error_generic': "❌ Произошла ошибка.",
        'unauthorized_action': "⛔️ У вас нет прав для выполнения этого действия.",
        'data_not_found_error': "Произошла ошибка, данные не найдены. Попробуйте снова.",
        'loading_please_wait': "⏳ Пожалуйста, подождите...",
        'action_cancelled': "Действие отменено.",
        'page_of': "Страница {page} из {total_pages}",
        'yes_button': "✅ Да",
        'no_button': "❌ Нет",
        'skip_button': "⏩ Пропустить",

        # show_profile
        'level_field': "▪️ Уровень:",
        'all_disciplines': "Все",
        'error_unauthorized': "❌ Не удалось определить вашу роль. Попробуйте авторизоваться снова.",

        'auth_role_approved_user': "🎉 Ваша роль «{role}» подтверждена!",

        # --- Главное меню ---
        'main_menu_title': "🏠 Главное меню",
        'submit_roster_button': "📋 Подать табель на сегодня",
        'form_report_button': "📝 Формировать отчет",
        'view_reports_button': "📊 Посмотреть отчеты",
        'profile_button': "👤 Профиль",
        'auth_button': "🔐 Авторизоваться",
        'manage_button': "⚙️ Управление",
        'reports_group_button': "➡️ Перейти в группу отчетов",
        'roster_summary_today': "\n\n📋 *Табель на сегодня:*",
        'roster_composition': "▪️ *Состав:* {details}",
        'total_declared': "▪️ *Всего заявлено:* {total} чел.",
        'completion_status': "\n\n📊 *Статус выполнения:*",
        'assigned_in_reports': "▪️ Задействовано в отчетах: *{assigned}* чел.",
        'free_in_reserve': "▪️ Свободно в резерве: *{reserve}* чел.",

        # --- Регистрация и Профиль ---
        'auth_prompt_role': "🔐 *Выберите вашу будущую роль:*",
        'auth_role_manager': "Руководитель",
        'auth_role_foreman': "Бригадир",
        'auth_role_pto': "ПТО",
        'auth_role_kiok': "КИОК",
        'auth_prompt_name': "📝 *Введите ваше имя и фамилию через пробел* (например: Иван Иванов):",
        'auth_error_name': "❗ *Ошибка: Введите и имя, и фамилию через пробел.*\n\n📝 *Пожалуйста, повторите ввод:*",
        'auth_prompt_contact': "📞 *Отлично! Теперь нажмите на кнопку ниже, чтобы отправить ваш контакт.*",
        'auth_contact_button': "📞 Отправить мой контакт",
        'auth_prompt_manager_level': "⚙️ *Последний шаг: выберите ваш уровень руководства:*",
        'auth_manager_level1': "Уровень 1 (полный доступ)",
        'auth_manager_level2': "Уровень 2 (по дисциплине)",
        'auth_prompt_discipline': "⚙️ *Последний шаг: выберите вашу дисциплину для роли «{role}»:*",
        'auth_prompt_discipline_manager': "⚙️ *...и вашу дисциплину для Уровня 2:*",
        'auth_pending_approval': "✅ *Данные приняты.*\n\n*Ваш запрос отправлен на подтверждение. Ожидайте...*",
        'auth_request_title': "🔐 *Запрос на регистрацию*",
        'auth_request_rejected_user': "❌ *Ваш запрос на роль «{role}» был отклонен.*",
        'auth_request_approved_admin': "✅ *Роль «{role}» для {name} подтверждена.*",
        'auth_request_rejected_admin': "❌ *Запрос для {name} отклонен.*",
        'profile_title': "👤 Ваш профиль:",
        'user_id_field': "▪️ UserID:",
        'phone_field': "▪️ Телефон:",
        'username_field': "▪️ Username:",
        'role_field': "▪️ Роль:",
        'brigade_field': "▪️ Бригада:",
        'discipline_field': "▪️ Дисциплина:",
        'level_field': "▪️ Уровень:",
        
        # --- Создание Отчета ---
        'report_step1_discipline': "📝 *Шаг 1: Для какой дисциплины создается отчет?*",
        'report_step1_corpus': "📝 *Шаг 1: Выберите корпус*",
        'report_step2_work_type': "📝 *Шаг 2: Выберите вид работ для «{discipline}»*",
        'report_step3_people_count': "📝 *Шаг 3: Укажите количество человек на объекте*",
        'report_step4_volume': "📝 *Шаг 4: Укажите выполненный объем в {unit}:*",
        'report_step4_volume_no_unit': "📝 *Шаг 4: Укажите выполненный объем:*",
        'report_step5_date': "📝 *Шаг 5: Выберите дату или введите ее вручную (ДД.ММ.ГГГГ)*",
        'report_step6_notes_prompt': "📝 *Шаг 6: Хотите добавить примечание?*\n_(номер чертежа, оси, проблемы и т.д.)_",
        'report_add_note_button': "✅ Да, добавить",
        'report_final_confirmation_title': "📋 *Проверьте и подтвердите ваш отчет:*\n",
        'report_confirm_and_send_button': "✅ Подтвердить и отправить",
        'report_error_no_roster': "⚠️ *Сначала нужно подать табель на сегодня!* \n\nВоспользуйтесь кнопкой в главном меню, чтобы заявить состав вашей бригады.",
        'report_error_no_people': "❌ *Ошибка!* Вы пытаетесь задействовать *{count}* чел., но в резерве осталось только *{reserve}*.\n\nВведите корректное число.",
        'report_note_prompt': "✍️ Введите ваше примечание одним сообщением:",
        'report_saved_and_sent': "✅ Отчет успешно сохранен и отправлен!",
        'report_saved_not_sent_error': "⚠️ *Отчет сохранен, но не может быть отправлен на согласование!*\n\nПричина: для дисциплины «*{discipline}*» не настроена тема в группе.\n\nПопросите администратора зайти в нужную тему и написать команду:\n`/link_topic {discipline}`",
        'report_new_from_foreman': "📄 *Новый отчет от бригадира: {foreman}* (ID: {report_id})\n",
        'report_status_pending': "*Статус:* ⏳ Ожидает согласования КИОК",
        'report_status_approved': "*Статус:* ✅ Согласовано: {approver}",
        'report_status_rejected': "*Статус:* ❌ Отклонено: {approver}",
        
        # --- Табель (Roster) ---
        'roster_already_submitted': "⚠️ Вы уже подавали табель на сегодня.",
        'roster_prompt': "📋 *Подача табеля на {date}*\n\nВведите количество человек для каждой должности **через запятую**, строго в указанном порядке.\nНапример, если у вас 5 сварщиков и 10 монтажников, введите: `5, 10`\n\n**Ваш порядок:**\n{roles_list}",
        'roster_confirm_prompt': "*Проверьте данные:*\n{summary}\n\n*Итого: {total} чел.*",
        'roster_confirm_and_save_button': "✅ Все верно, подтвердить",
        'roster_error_mismatch': "❌ *Ошибка!* Вы ввели {input_count} чисел, а ожидалось {expected_count}. Пожалуйста, введите количество для каждой должности из списка.",
        'roster_saved_safely': "✅ *Табель на сегодня успешно принят!*\n\nВ вашем резерве осталось *{reserve}* чел.",
        'roster_dangerous_save_warning': "‼️ *ВНИМАНИЕ!* ‼️\n\nВы пытаетесь заявить *{new_total}* чел., но в отчетах за сегодня уже задействовано *{assigned}* чел.\n\nПри подтверждении **все ваши отчеты за сегодня будут УДАЛЕНЫ**, и вам придется распределять людей заново.\n\nВы уверены, что хотите продолжить?",
        'roster_force_save_button': "✅ Да, удалить отчеты и сохранить",
        'roster_force_saved_success': "✅ *Ваши отчеты за сегодня были удалены. Новый табель принят!*",

       
        'forward_button': "Вперёд ▶️",
        'today_button': "Сегодня",
        'yesterday_button': "Вчера",

        'report_error_no_work_types': "⚠️ *Ошибка:* Не найдено ни одного вида работ для дисциплины «{discipline}».",

        'report_error_invalid_number': "❗*Ошибка:* Пожалуйста, введите количество человек одним положительным числом (например: 5).",
        'report_error_invalid_volume': "❗*Ошибка:* Пожалуйста, введите выполненный объем одним числом (можно дробным).",
        'report_error_invalid_date': "❗*Ошибка:* Неверный формат даты.\n\n📝 *Выберите дату кнопкой или введите ее вручную (ДД.ММ.ГГГГ)*",
        'report_summary_corpus': "▪️ *Корпус:*",
        'report_summary_work_type': "▪️ *Вид работ:*",
        'report_summary_date': "▪️ *Дата:*",
        'report_summary_people': "▪️ *Кол-во человек:*",
        'report_summary_volume': "▪️ *Выполненный объем:*",
        'report_summary_notes': "▪️ *Примечание:*",

        'report_creation_cancelled': "Создание отчета отменено",
        'report_saving_and_sending': "⏳ Сохраняю отчет и отправляю в группу...",
        'report_error_db_save': "❌ *Произошла ошибка при сохранении отчета в базу данных.*",
        'report_accepted_greeting': "✅ Ваш отчет принят.",
        
        'report_error_no_discipline': "❌ Ошибка: не удалось определить дисциплину для отчета.",
        'report_error_group_send': "❌ *Произошла ошибка при отправке отчета в группу.*",

        'roster_error_invalid_format': "❌ *Ошибка формата!* Пожалуйста, введите только числа, разделенные запятой (например: `5, 10`)",
        'roster_error_no_people': "❌ *Ошибка!* Вы не указали ни одного человека. Введите корректные данные.",

        'personnel_history_title': "История табелей",
'roster_for_period_title': "Табели по дисциплине «{discipline}» за {period}",
'no_rosters_for_period': "На выбранный период по дисциплине «{discipline}» табели не поданы.",
'pick_date_button': "Выбрать дату",
'all_disciplines_option': "Все дисциплины",
'history_prompt_date': "📅 *Введите дату (ДД.ММ.ГГГГ)* или диапазон дат через запятую (например, `01.07.2025, 07.07.2025`):",
'all_time_button': "Все время",

'report_menu_summary_title': "Общая сводка ({period})",
'total_brigades_in_system': "Всего бригад в системе:",
'brigades_in_discipline': "Бригад в дисциплине:",
'summary_for_your_brigade': "Сводка по вашей бригаде ({period})",
'reports_for_period': "Отчётов за период:",
'reports_approved': "✅ Согласовано:",
'reports_rejected': "❌ Отклонено:",
'reports_pending': "⏳ Ожидает:",
'select_report_detail': "Выберите детализацию отчёта:",
'all_time_button': "Все время",
'foreman_performance_button': "📊 Моя выработка",
'personnel_status_button': "👥 Статус персонала",
'back_to_main_menu_button': "🏠 В главное меню",
'report_overview_button': "📊 Общий обзор (график)",
'problem_brigades_button': "⚠️ Проблемные бригады",
'historical_overview_button': "📅 Исторический обзор",
'export_excel_button': "📤 Экспорт в Excel",
'delete_report_button': "🗑️ Удалить отчет",

'problem_brigades_title': "Проблемные бригады: {discipline}",
'problem_brigades_no_report_header': "🔴 Не сдали отчет сегодня:",
'problem_brigades_low_performance_header': "🟠 Низкая выработка (в среднем):",
'problem_brigades_no_issues': "✅ По дисциплине «{discipline}» проблемных бригад не найдено!",
'problem_brigades_avg_output_label': "Выработка",

'low_performance_brigade_count': "📉 Бригад с низкой выработкой: *{count}*",

'hr_menu_button': "👥 Людские ресурсы",
'hr_menu_title': "Меню «Людские ресурсы»",
'hr_menu_status_button': "📊 Статус персонала на сегодня",
'hr_menu_history_button': "🗓️ История табелей",
'detail_by_discipline_button': "Детально по «{discipline}»",

'hr_summary_title': "👥 Общая сводка по персоналу на сегодня",
'total_people_today': "▪️ Всего заявлено сегодня: *{total}* чел.",
'no_rosters_today': "На сегодня табели еще не поданы.",
'roster_details_by_brigade_title': "👥 Детализация по «{discipline}» за {period}",

'hr_discipline_select_prompt': "Выберите дисциплину для просмотра детализации:",
'hr_report_title': "Детализация по «{discipline}» за {date}",
'hr_report_summary': "▪️ Заявлено: *{total_people}* чел. ▪️ Сдали табель: *{brigade_count}* бригад",

'main_menu_roster_summary_compact': "Табель на сегодня: *{total}* чел. (в резерве: *{reserve}*)",

'change_language_button': "🌐 Язык",

'foreman_performance_analyzing': "⏳ Анализирую вашу выработку...",
'foreman_performance_title': "📊 Ваша выработка (последние 5 отчетов)",
'foreman_performance_no_reports': "У вас пока нет сданных отчетов.",
'foreman_performance_avg_label': "▪️ Средний процент выполнения нормы:",
'foreman_performance_volume_label': "Объем",
'foreman_performance_output_label': "Выработка",
'foreman_performance_back_button': "◀️ Назад к выбору отчета",

'overview_summary_title': "📊 Сводка План/Факт на сегодня (без учета согласования)",
'overview_no_data': "Нет данных для построения сводки.",

'loading_please_wait': 'Загрузка, пожалуйста, подождите...',
        'overview_summary_title': 'Сводка План/Факт на сегодня',
        'overview_discipline_summary': '📊 *{discipline}* (Всего: {people} чел. | Ср. выработка: {performance}%)',
        'overview_work_type_line': '{work_type}: Ф: {fact:.1f} / П: {plan:.1f} / В-ка: {percent:.1f}%',
        'overview_select_chart_prompt': 'Выберите дисциплину для просмотра графика:',
        'no_reports_for_other_disciplines': 'По остальным дисциплинам сегодня отчеты не поданы.',
        'overview_no_data': 'Пока нет данных для отображения сводки.', # Если эта строка была удалена, верните ее.
        'error_generic': 'Произошла ошибка. Пожалуйста, попробуйте еще раз.',
        'back_button': '◀️ Назад',

        'overview_summary_title': 'Сводка План/Факт на сегодня',
        'total_label': 'Всего',
        'people_label': 'чел.',
        'avg_output_label': 'Ср. выработка',
        'fact_short_label': 'Ф',
        'plan_short_label': 'П',
        'output_short_label': 'В-ка',
        'overview_no_data_for_discipline': 'отчетов не подано',
        'overview_no_reports_overall': 'По всем дисциплинам сегодня отчеты не поданы.',
        'overview_select_chart_prompt': 'Выберите дисциплину для просмотра графика:',
        'back_button': '◀️ Назад',
        'loading_please_wait': 'Загружаю, пожалуйста, подождите...',
        'overview_no_disciplines_error': 'В базе данных нет дисциплин. Обратитесь к администратору.',
        'error_generic': 'Произошла непредвиденная ошибка. Пожалуйста, попробуйте позже.',

        # --- Переводы, которые могут использоваться также в generate_overview_chart ---
        'generating_dashboard_for': 'Формирую дашборд для «{}»...',
        'no_data_for_dashboard': 'Нет данных для построения дашборда по дисциплине «{}».',
        'no_chart_data_excluding_other': 'Нет данных для построения графика по дисциплине «{}» (исключены "Прочие" работы).',
        'fact_label': 'Факт', # Полное название для графика
        'plan_label': 'План', # Полное название для графика
        'work_output_chart_title': 'Выработка по видам работ: {}',
        'total_volume_label': 'Суммарный объем',
        'legend_label': 'Легенда',
        'dashboard_caption_title': 'Дашборд по дисциплине «{}»',
        'data_period': 'Данные за период с {} по {}',

        'total_people_short': 'Всего людей',
'average_output_short': 'Средняя выработка',
'work_details_label': 'Детализация по работам:',
'other_works_label': 'Прочие работы',
'no_reports_for_period': 'Нет отчетов за выбранный период',

    },
    'en': {
        # --- General ---
        'language_prompt': "Please select your language:",
        'language_changed': "✅ Language changed to English.",
        'back_button': "◀️ Back",
        'cancel_button': "❌ Cancel",
        'confirm_button': "✅ Confirm",
        'error_generic': "❌ An error occurred.",
        'unauthorized_action': "⛔️ You do not have permission to perform this action.",
        'data_not_found_error': "An error occurred, data not found. Please try again.",
        'loading_please_wait': "⏳ Please wait...",
        'action_cancelled': "Action cancelled.",
        'page_of': "Page {page} of {total_pages}",
        'yes_button': "✅ Yes",
        'no_button': "❌ No",
        'skip_button': "⏩ Skip",

        # show_profile
        'level_field': "▪️ Level:",
        'all_disciplines': "All",
        'error_unauthorized': "❌ Could not determine your role. Please try to authorize again.",

        'auth_role_approved_user': "🎉 Your role «{role}» has been confirmed!",


        # --- Main Menu ---
        'main_menu_title': "🏠 Main Menu",
        'submit_roster_button': "📋 Submit Roster for Today",
        'form_report_button': "📝 Create Report",
        'view_reports_button': "📊 View Reports",
        'profile_button': "👤 Profile",
        'auth_button': "🔐 Authorize",
        'manage_button': "⚙️ Management",
        'reports_group_button': "➡️ Go to reports group",
        'roster_summary_today': "\n\n📋 *Roster for today:*",
        'roster_composition': "▪️ *Composition:* {details}",
        'total_declared': "▪️ *Total declared:* {total} people",
        'completion_status': "\n\n📊 *Completion Status:*",
        'assigned_in_reports': "▪️ Assigned in reports: *{assigned}* people",
        'free_in_reserve': "▪️ Free in reserve: *{reserve}* people",

        # --- Auth & Profile ---
        'auth_prompt_role': "🔐 *Choose your future role:*",
        'auth_role_manager': "Manager",
        'auth_role_foreman': "Foreman",
        'auth_role_pto': "PTO",
        'auth_role_kiok': "QCC",
        'auth_prompt_name': "📝 *Enter your first and last name* (e.g., John Smith):",
        'auth_error_name': "❗ *Error: Please enter both first and last name, separated by a space.*\n\n📝 *Please try again:*",
        'auth_prompt_contact': "📞 *Great! Now press the button below to share your contact information.*",
        'auth_contact_button': "📞 Share my contact",
        'auth_prompt_manager_level': "⚙️ *Final step: choose your management level:*",
        'auth_manager_level1': "Level 1 (full access)",
        'auth_manager_level2': "Level 2 (by discipline)",
        'auth_prompt_discipline': "⚙️ *Final step: choose your discipline for the «{role}» role:*",
        'auth_prompt_discipline_manager': "⚙️ *...and your discipline for Level 2:*",
        'auth_pending_approval': "✅ *Data received.*\n\n*Your request has been sent for confirmation. Please wait...*",
        'auth_request_title': "🔐 *Registration Request*",
        'auth_request_rejected_user': "❌ *Your request for the «{role}» role was rejected.*",
        'auth_request_approved_admin': "✅ *The «{role}» role for {name} has been confirmed.*",
        'auth_request_rejected_admin': "❌ *The request for {name} was rejected.*",
        'profile_title': "👤 Your Profile:",
        'user_id_field': "▪️ UserID:",
        'phone_field': "▪️ Phone:",
        'username_field': "▪️ Username:",
        'role_field': "▪️ Role:",
        'brigade_field': "▪️ Brigade:",
        'discipline_field': "▪️ Discipline:",
        'level_field': "▪️ Level:",
        
        # --- Report Creation ---
        'report_step1_discipline': "📝 *Step 1: Which discipline is this report for?*",
        'report_step1_corpus': "📝 *Step 1: Select the building*",
        'report_step2_work_type': "📝 *Step 2: Select the work type for «{discipline}»*",
        'report_step3_people_count': "📝 *Step 3: Specify the number of people on site*",
        'report_step4_volume': "📝 *Step 4: Specify the completed volume in {unit}:*",
        'report_step4_volume_no_unit': "📝 *Step 4: Specify the completed volume:*",
        'report_step5_date': "📝 *Step 5: Select a date or enter it manually (DD.MM.YYYY)*",
        'report_step6_notes_prompt': "📝 *Step 6: Would you like to add a note?*\n_(drawing number, axes, issues, etc.)_",
        'report_add_note_button': "✅ Yes, add note",
        'report_final_confirmation_title': "📋 *Please check and confirm your report:*\n",
        'report_confirm_and_send_button': "✅ Confirm and send",
        'report_error_no_roster': "⚠️ *You must submit a roster for today first!* \n\nPlease use the button in the main menu to declare your brigade's composition.",
        'report_error_no_people': "❌ *Error!* You are trying to assign *{count}* people, but only *{reserve}* are left in the reserve.\n\nPlease enter a correct number.",
        'report_note_prompt': "✍️ Please enter your note in a single message:",
        'report_saved_and_sent': "✅ Report successfully saved and sent!",
        'report_saved_not_sent_error': "⚠️ *Report saved, but cannot be sent for approval!*\n\nReason: a group topic has not been configured for the «*{discipline}*» discipline.\n\nPlease ask an administrator to go to the correct topic and type the command:\n`/link_topic {discipline}`",
        'report_new_from_foreman': "📄 *New report from foreman: {foreman}* (ID: {report_id})\n",
        'report_status_pending': "*Status:* ⏳ Awaiting QCC approval",
        'report_status_approved': "*Status:* ✅ Approved by: {approver}",
        'report_status_rejected': "*Status:* ❌ Rejected by: {approver}",

        # --- Roster ---
        'roster_already_submitted': "⚠️ You have already submitted the roster for today.",
        'roster_prompt': "📋 *Submitting roster for {date}*\n\nPlease enter the number of people for each position, **separated by a comma**, strictly in the order shown.\nFor example, if you have 5 welders and 10 fitters, enter: `5, 10`\n\n**Your order is:**\n{roles_list}",
        'roster_confirm_prompt': "*Please check the data:*\n{summary}\n\n*Total: {total} people*",
        'roster_confirm_and_save_button': "✅ Correct, confirm",
        'roster_error_mismatch': "❌ *Error!* You entered {input_count} numbers, but {expected_count} were expected. Please enter a number for each position from the list.",
        'roster_saved_safely': "✅ *Roster for today successfully submitted!*\n\nYou have *{reserve}* people left in your reserve.",
        'roster_dangerous_save_warning': "‼️ *ATTENTION!* ‼️\n\nYou are trying to declare *{new_total}* people, but *{assigned}* are already assigned in today's reports.\n\nUpon confirmation, **all of your reports for today will be DELETED**, and you will have to reassign personnel.\n\nAre you sure you want to continue?",
        'roster_force_save_button': "✅ Yes, delete reports and save",
        'roster_force_saved_success': "✅ *Your reports for today have been deleted. The new roster has been submitted!*",

        'forward_button': "Forward ▶️",
        'today_button': "Today",
        'yesterday_button': "Yesterday",

        'report_error_no_work_types': "⚠️ *Error:* No work types found for the «{discipline}» discipline.",

        'report_error_invalid_number': "❗*Error:* Please enter the number of people as a single positive number (e.g., 5).",
        'report_error_invalid_volume': "❗*Error:* Please enter the completed volume as a single number (can be fractional).",
        'report_error_invalid_date': "❗*Error:* Invalid date format.\n\n📝 *Select a date with a button or enter it manually (DD.MM.YYYY)*",
        'report_summary_corpus': "▪️ *Building:*",
        'report_summary_work_type': "▪️ *Work Type:*",
        'report_summary_date': "▪️ *Date:*",
        'report_summary_people': "▪️ *People Count:*",
        'report_summary_volume': "▪️ *Completed Volume:*",
        'report_summary_notes': "▪️ *Note:*",
        'report_creation_cancelled': "Report creation cancelled",
        'report_saving_and_sending': "⏳ Saving report and sending to group...",
        'report_error_db_save': "❌ *An error occurred while saving the report to the database.*",
        'report_accepted_greeting': "✅ Your report has been accepted.",

        'report_error_no_discipline': "❌ Error: Could not determine the discipline for the report.",
        'report_error_group_send': "❌ *An error occurred while sending the report to the group.*",

        'roster_error_invalid_format': "❌ *Format error!* Please enter only numbers, separated by a comma (e.g., `5, 10`)",
        'roster_error_no_people': "❌ *Error!* You haven't specified any people. Please enter correct data.",

        'personnel_history_title': "Personnel Rosters History",
'roster_for_period_title': "Rosters for «{discipline}» discipline for {period}",
'no_rosters_for_period': "No rosters submitted for the «{discipline}» discipline for the selected period.",
'pick_date_button': "Select Date",
'all_disciplines_option': "All Disciplines",
'history_prompt_date': "📅 *Enter a date (DD.MM.YYYY)* or a date range separated by a comma (e.g., `01.07.2025, 07.07.2025`):",
'all_time_button': "All Time",

'report_menu_summary_title': "Overall Summary ({period})",
'total_brigades_in_system': "Total brigades in system:",
'brigades_in_discipline': "Brigades in discipline:",
'summary_for_your_brigade': "Summary for your brigade ({period})",
'reports_for_period': "Reports for the period:",
'reports_approved': "✅ Approved:",
'reports_rejected': "❌ Rejected:",
'reports_pending': "⏳ Pending:",
'select_report_detail': "Select report details:",
'all_time_button': "All Time",
'foreman_performance_button': "📊 My Performance",
'personnel_status_button': "👥 Personnel Status",
'back_to_main_menu_button': "🏠 Main Menu",
'report_overview_button': "📊 General Overview (chart)",
'problem_brigades_button': "⚠️ Problem Brigades",
'historical_overview_button': "📅 Historical Overview",
'export_excel_button': "📤 Export to Excel",
'delete_report_button': "🗑️ Delete Report",

'problem_brigades_title': "Problem Brigades: {discipline}",
'problem_brigades_no_report_header': "🔴 Did not submit a report today:",
'problem_brigades_low_performance_header': "🟠 Low Performance (on average):",
'problem_brigades_no_issues': "✅ No problem brigades found for «{discipline}» discipline!",
'problem_brigades_avg_output_label': "Performance",

'low_performance_brigade_count': "📉 Brigades with low performance: *{count}*",

'hr_menu_button': "👥 Human Resources",
'hr_menu_title': "Human Resources Menu",
'hr_menu_status_button': "📊 Personnel Status for Today",
'hr_menu_history_button': "🗓️ Roster History",
'detail_by_discipline_button': "Details for «{discipline}»",

'hr_summary_title': "👥 Overall Personnel Summary for Today",
'total_people_today': "▪️ Total declared today: *{total}* people",
'no_rosters_today': "No rosters have been submitted for today yet.",
'roster_details_by_brigade_title': "👥 Details for «{discipline}» for {period}",

'hr_discipline_select_prompt': "Select a discipline to view details:",
'hr_report_title': "Details for «{discipline}» for {date}",
'hr_report_summary': "▪️ Declared: *{total_people}* people ▪️ Rosters submitted: *{brigade_count}* brigades",

'main_menu_roster_summary_compact': "Roster for today: *{total}* people (in reserve: *{reserve}*)",

'change_language_button': "🌐 Language",

'foreman_performance_analyzing': "⏳ Analyzing your performance...",
'foreman_performance_title': "📊 Your Performance (last 5 reports)",
'foreman_performance_no_reports': "You have no submitted reports yet.",
'foreman_performance_avg_label': "▪️ Average percentage of norm completion:",
'foreman_performance_volume_label': "Volume",
'foreman_performance_output_label': "Performance",
'foreman_performance_back_button': "◀️ Back to report selection",

'overview_summary_title': "📊 Сводка План/Факт на сегодня (без учета согласования)",
'overview_no_data': "Нет данных для построения сводки.",

'loading_please_wait': 'Loading, please wait...',
        'overview_summary_title': 'Plan/Fact Summary for Today',
        'overview_discipline_summary': '📊 *{discipline}* (Total: {people} pers. | Avg. Output: {performance}%)',
        'overview_work_type_line': '{work_type}: F: {fact:.1f} / P: {plan:.1f} / Output: {percent:.1f}%',
        'overview_select_chart_prompt': 'Select a discipline to view the chart:',
        'no_reports_for_other_disciplines': 'No reports submitted for other disciplines today.',
        'overview_no_data': 'No data available for the overview yet.',
        'error_generic': 'An error occurred. Please try again.',
        'back_button': '◀️ Back',

        'overview_summary_title': 'Plan/Fact Summary for Today',
        'total_label': 'Total',
        'people_label': 'ppl.',
        'avg_output_label': 'Avg. Output',
        'fact_short_label': 'F',
        'plan_short_label': 'P',
        'output_short_label': 'Out',
        'overview_no_data_for_discipline': 'no reports submitted',
        'overview_no_reports_overall': 'No reports submitted for any discipline today.',
        'overview_select_chart_prompt': 'Select a discipline to view the chart:',
        'back_button': '◀️ Back',
        'loading_please_wait': 'Loading, please wait...',
        'overview_no_disciplines_error': 'No disciplines found in the database. Please contact the administrator.',
        'error_generic': 'An unexpected error occurred. Please try again later.',

        'generating_dashboard_for': 'Generating dashboard for «{}»...',
        'no_data_for_dashboard': 'No data to build a dashboard for discipline «{}».',
        'no_chart_data_excluding_other': 'No chart data for discipline «{}» (excluding "Other" works).',
        'fact_label': 'Fact',
        'plan_label': 'Plan',
        'work_output_chart_title': 'Output by Work Type: {}',
        'total_volume_label': 'Total Volume',
        'legend_label': 'Legend',
        'dashboard_caption_title': 'Dashboard for discipline «{}»',
        'data_period': 'Data for the period from {} to {}',

    },
    'uz': {
        # --- Umumiy ---
        'language_prompt': "Iltimos, tilingizni tanlang:",
        'language_changed': "✅ Til O'zbekchaga o'zgartirildi.",
        'back_button': "◀️ Orqaga",
        'cancel_button': "❌ Bekor qilish",
        'confirm_button': "✅ Tasdiqlash",
        'error_generic': "❌ Xatolik yuz berdi.",
        'unauthorized_action': "⛔️ Bu amalni bajarish uchun sizda ruxsat yo'q.",
        'data_not_found_error': "Xatolik yuz berdi, ma'lumotlar topilmadi. Iltimos, qaytadan urining.",
        'loading_please_wait': "⏳ Iltimos, kuting...",
        'action_cancelled': "Amal bekor qilindi.",
        'page_of': "{total_pages} dan {page}-sahifa",
        'yes_button': "✅ Ha",
        'no_button': "❌ Yo'q",
        'skip_button': "⏩ O'tkazib yuborish",

        # show_profile
        'level_field': "▪️ Daraja:",
        'all_disciplines': "Barchasi",
        'error_unauthorized': "❌ Rolingizni aniqlab boʻlmadi. Iltimos, qaytadan avtorizatsiyadan oʻting.",

        'auth_role_approved_user': "🎉 Sizning «{role}» rolingiz tasdiqlandi!",

        # --- Asosiy Menyu ---
        'main_menu_title': "🏠 Asosiy menyu",
        'submit_roster_button': "📋 Bugungi tabelni yuborish",
        'form_report_button': "📝 Hisobot yaratish",
        'view_reports_button': "📊 Hisobotlarni ko'rish",
        'profile_button': "👤 Profil",
        'auth_button': "🔐 Avtorizatsiya",
        'manage_button': "⚙️ Boshqaruv",
        'reports_group_button': "➡️ Hisobotlar guruhiga o'tish",
        'roster_summary_today': "\n\n📋 *Bugungi tabel:*",
        'roster_composition': "▪️ *Tarkib:* {details}",
        'total_declared': "▪️ *Jami arizada:* {total} kishi",
        'completion_status': "\n\n📊 *Bajarilish holati:*",
        'assigned_in_reports': "▪️ Hisobotlarda band: *{assigned}* kishi",
        'free_in_reserve': "▪️ Rezervda bo'sh: *{reserve}* kishi",

        # --- Avtorizatsiya & Profil ---
        'auth_prompt_role': "🔐 *Kelajakdagi rolingizni tanlang:*",
        'auth_role_manager': "Rahbar",
        'auth_role_foreman': "Brigadir",
        'auth_role_pto': "ITB (PTO)",
        'auth_role_kiok': "SIK (QCC)",
        'auth_prompt_name': "📝 *Ism va familiyangizni kiriting* (masalan: Alisher Usmonov):",
        'auth_error_name': "❗ *Xato: Iltimos, ism va familiyani bo'sh joy bilan ajratib kiriting.*\n\n📝 *Iltimos, qaytadan kiriting:*",
        'auth_prompt_contact': "📞 *Ajoyib! Endi kontaktingizni yuborish uchun quyidagi tugmani bosing.*",
        'auth_contact_button': "📞 Kontaktimni yuborish",
        'auth_prompt_manager_level': "⚙️ *Oxirgi qadam: boshqaruv darajangizni tanlang:*",
        'auth_manager_level1': "1-daraja (to'liq kirish)",
        'auth_manager_level2': "2-daraja (yo'nalish bo'yicha)",
        'auth_prompt_discipline': "⚙️ *Oxirgi qadam: «{role}» roli uchun yo'nalishingizni tanlang:*",
        'auth_prompt_discipline_manager': "⚙️ *...va 2-daraja uchun yo'nalishingizni tanlang:*",
        'auth_pending_approval': "✅ *Ma'lumotlar qabul qilindi.*\n\n*Sizning so'rovingiz tasdiqlash uchun yuborildi. Iltimos, kuting...*",
        'auth_request_title': "🔐 *Ro'yxatdan o'tish so'rovi*",
        'auth_request_rejected_user': "❌ *Sizning «{role}» roli uchun so'rovingiz rad etildi.*",
        'auth_request_approved_admin': "✅ *{name} uchun «{role}» roli tasdiqlandi.*",
        'auth_request_rejected_admin': "❌ *{name} uchun so'rov rad etildi.*",
        'profile_title': "👤 Sizning profilingiz:",
        'user_id_field': "▪️ UserID:",
        'phone_field': "▪️ Telefon:",
        'username_field': "▪️ Username:",
        'role_field': "▪️ Rol:",
        'brigade_field': "▪️ Brigada:",
        'discipline_field': "▪️ Yo'nalish:",
        'level_field': "▪️ Daraja:",

        # --- Hisobot Yaratish ---
        'report_step1_discipline': "📝 *1-qadam: Hisobot qaysi yo'nalish uchun yaratilmoqda?*",
        'report_step1_corpus': "📝 *1-qadam: Korpusni tanlang*",
        'report_step2_work_type': "📝 *2-qadam: «{discipline}» uchun ish turini tanlang*",
        'report_step3_people_count': "📝 *3-qadam: Ob'ektdagi odamlar sonini kiriting*",
        'report_step4_volume': "📝 *4-qadam: Bajarilgan hajmni {unit}da kiriting:*",
        'report_step4_volume_no_unit': "📝 *4-qadam: Bajarilgan hajmni kiriting:*",
        'report_step5_date': "📝 *5-qadam: Sanani tanlang yoki qo'lda kiriting (KK.OO.YYYY)*",
        'report_step6_notes_prompt': "📝 *6-qadam: Izoh qo'shishni xohlaysizmi?*\n_(chizma raqami, o'qlar, muammolar va hk.)_",
        'report_add_note_button': "✅ Ha, qo'shish",
        'report_final_confirmation_title': "📋 *Iltimos, hisobotingizni tekshiring va tasdiqlang:*\n",
        'report_confirm_and_send_button': "✅ Tasdiqlash va yuborish",
        'report_error_no_roster': "⚠️ *Avval bugungi tabelni topshirishingiz kerak!* \n\nBrigadangiz tarkibini e'lon qilish uchun asosiy menyudagi tugmadan foydalaning.",
        'report_error_no_people': "❌ *Xato!* Siz *{count}* kishini jalb qilmoqchisiz, lekin rezervda faqat *{reserve}* kishi qolgan.\n\nTo'g'ri raqamni kiriting.",
        'report_note_prompt': "✍️ Izohingizni bitta xabarda kiriting:",
        'report_saved_and_sent': "✅ Hisobot muvaffaqiyatli saqlandi va yuborildi!",
        'report_saved_not_sent_error': "⚠️ *Hisobot saqlandi, lekin kelishuvga yuborib bo'lmadi!*\n\nSabab: «*{discipline}*» yo'nalishi uchun guruhda mavzu sozlanmagan.\n\nAdministratorga kerakli mavzuga kirib, buyruqni yozishini so'rang:\n`/link_topic {discipline}`",
        'report_new_from_foreman': "📄 *Brigadirdan yangi hisobot: {foreman}* (ID: {report_id})\n",
        'report_status_pending': "*Holat:* ⏳ SIK (QCC) kelishuvi kutilmoqda",
        'report_status_approved': "*Holat:* ✅ Kelishildi: {approver}",
        'report_status_rejected': "*Holat:* ❌ Rad etildi: {approver}",

        # --- Tabel ---
        'roster_already_submitted': "⚠️ Siz bugungi tabelni allaqachon topshirgansiz.",
        'roster_prompt': "📋 *{date} uchun tabel topshirish*\n\nHar bir lavozim uchun odamlar sonini ko'rsatilgan tartibda, **vergul bilan ajratib** kiriting.\nMasalan, 5 ta payvandchi va 10 ta montajchi bo'lsa, kiriting: `5, 10`\n\n**Sizning tartibingiz:**\n{roles_list}",
        'roster_confirm_prompt': "*Ma'lumotlarni tekshiring:*\n{summary}\n\n*Jami: {total} kishi*",
        'roster_confirm_and_save_button': "✅ To'g'ri, tasdiqlayman",
        'roster_error_mismatch': "❌ *Xato!* Siz {input_count} ta raqam kiritdingiz, lekin {expected_count} ta kutilgan edi. Iltimos, ro'yxatdagi har bir lavozim uchun son kiriting.",
        'roster_saved_safely': "✅ *Bugungi tabel muvaffaqiyatli qabul qilindi!*\n\nSizning reservingizda *{reserve}* kishi qoldi.",
        'roster_dangerous_save_warning': "‼️ *DIQQAT!* ‼️\n\nSiz *{new_total}* kishini e'lon qilmoqchisiz, lekin bugungi hisobotlarda allaqachon *{assigned}* kishi band.\n\nTasdiqlaganingizdan so'ng, **bugungi barcha hisobotlaringiz O'CHIRILADI** va xodimlarni qaytadan taqsimlashingiz kerak bo'ladi.\n\nDavom etishni xohlaysizmi?",
        'roster_force_save_button': "✅ Ha, hisobotlarni o'chirib, saqlash",
        'roster_force_saved_success': "✅ *Bugungi hisobotlaringiz o'chirildi. Yangi tabel qabul qilindi!*",

        # Добавьте это в секцию 'uz'
        'forward_button': "Oldinga ▶️",
        'today_button': "Bugun",
        'yesterday_button': "Kecha",

        'report_error_no_work_types': "⚠️ *Xato:* «{discipline}» yo'nalishi uchun ish turlari topilmadi.",

        'report_error_invalid_number': "❗*Xato:* Iltimos, odamlar sonini bitta musbat son bilan kiriting (masalan: 5).",
        'report_error_invalid_volume': "❗*Xato:* Iltimos, bajarilgan hajmni bitta son bilan kiriting (kasr bo'lishi mumkin).",
        'report_error_invalid_date': "❗*Xato:* Sana formati noto'g'ri.\n\n📝 *Tugma yordamida sanani tanlang yoki qo'lda kiriting (KK.OO.YYYY)*",
        'report_summary_corpus': "▪️ *Korpus:*",
        'report_summary_work_type': "▪️ *Ish turi:*",
        'report_summary_date': "▪️ *Sana:*",
        'report_summary_people': "▪️ *Odamlar soni:*",
        'report_summary_volume': "▪️ *Bajarilgan hajm:*",
        'report_summary_notes': "▪️ *Izoh:*",

        'report_creation_cancelled': "Hisobot yaratish bekor qilindi",
        'report_saving_and_sending': "⏳ Hisobot saqlanmoqda va guruhga yuborilmoqda...",
        'report_error_db_save': "❌ *Hisobotni ma'lumotlar bazasiga saqlashda xatolik yuz berdi.*",
        'report_accepted_greeting': "✅ Sizning hisobotingiz qabul qilindi.",
        'report_error_no_discipline': "❌ Xato: Hisobot uchun yo'nalishni aniqlab bo'lmadi.",
        'report_error_group_send': "❌ *Hisobotni guruhga yuborishda xatolik yuz berdi.*",

        'roster_error_invalid_format': "❌ *Format xatosi!* Iltimos, faqat vergul bilan ajratilgan raqamlarni kiriting (masalan: `5, 10`)",
        'roster_error_no_people': "❌ *Xato!* Siz birorta ham odam ko'rsatmadingiz. To'g'ri ma'lumotlarni kiriting.",

        'personnel_history_title': "Tabel tarixi",
'roster_for_period_title': "«{discipline}» yo'nalishi bo'yicha {period} uchun tabel",
'no_rosters_for_period': "Tanlangan davr uchun «{discipline}» yo'nalishi bo'yicha tabellar topshirilmagan.",
'pick_date_button': "Sanani tanlash",
'all_disciplines_option': "Barcha yo'nalishlar",
'history_prompt_date': "📅 *Sana kiriting (KK.OO.YYYY)* yoki vergul bilan ajratilgan sana oralig'ini kiriting (masalan, `01.07.2025, 07.07.2025`):",
'all_time_button': "Butun vaqt",

'report_menu_summary_title': "Umumiy hisobot ({period})",
'total_brigades_in_system': "Tizimdagi jami brigadalar:",
'brigades_in_discipline': "Yo'nalishdagi brigadalar:",
'summary_for_your_brigade': "Sizning brigadangiz bo'yicha hisobot ({period})",
'reports_for_period': "Davr uchun hisobotlar:",
'reports_approved': "✅ Tasdiqlangan:",
'reports_rejected': "❌ Rad etilgan:",
'reports_pending': "⏳ Kutilmoqda:",
'select_report_detail': "Hisobot tafsilotlarini tanlang:",
'all_time_button': "Butun vaqt",
'foreman_performance_button': "📊 Mening samaradorligim",
'personnel_status_button': "👥 Xodimlar holati",
'back_to_main_menu_button': "🏠 Asosiy menyuga",
'report_overview_button': "📊 Umumiy ko'rinish (grafik)",
'problem_brigades_button': "⚠️ Muammoli brigadalar",
'historical_overview_button': "📅 Tarixiy ko'rinish",
'export_excel_button': "📤 Excelga eksport",
'delete_report_button': "🗑️ Hisobotni o'chirish",

'problem_brigades_title': "Muammoli brigadalar: {discipline}",
'problem_brigades_no_report_header': "🔴 Bugun hisobot topshirmaganlar:",
'problem_brigades_low_performance_header': "🟠 Past samaradorlik (o'rtacha):",
'problem_brigades_no_issues': "✅ «{discipline}» yo'nalishi bo'yicha muammoli brigadalar topilmadi!",
'problem_brigades_avg_output_label': "Samaradorlik",

'low_performance_brigade_count': "📉 Samaradorligi past brigadalar soni: *{count}*",

'hr_menu_button': "👥 Xodimlar bo'limi",
'hr_menu_title': "Xodimlar bo'limi menyusi",
'hr_menu_status_button': "📊 Bugungi xodimlar holati",
'hr_menu_history_button': "🗓️ Tabel tarixi",
'detail_by_discipline_button': "«{discipline}» bo'yicha batafsil",

'hr_summary_title': "👥 Bugungi xodimlar bo'yicha umumiy ma'lumot",
'total_people_today': "▪️ Bugun jami e'lon qilingan: *{total}* kishi",
'no_rosters_today': "Bugungi kun uchun hali tabel topshirilmagan.",
'roster_details_by_brigade_title': "👥 {period} uchun «{discipline}» bo'yicha tafsilotlar",

'hr_discipline_select_prompt': "Tafsilotlarni ko'rish uchun yo'nalishni tanlang:",
'hr_report_title': "{date} uchun «{discipline}» bo'yicha tafsilotlar",
'hr_report_summary': "▪️ E'lon qilingan: *{total_people}* kishi ▪️ Tabel topshirgan: *{brigade_count}* brigada",

'main_menu_roster_summary_compact': "Bugungi tabel: *{total}* kishi (rezervda: *{reserve}*)",

'change_language_button': "🌐 Til",

'foreman_performance_analyzing': "⏳ Analyzing your performance...",
'foreman_performance_title': "📊 Your Performance (last 5 reports)",
'foreman_performance_no_reports': "You have no submitted reports yet.",
'foreman_performance_avg_label': "▪️ Average percentage of norm completion:",
'foreman_performance_volume_label': "Volume",
'foreman_performance_output_label': "Performance",
'foreman_performance_back_button': "◀️ Back to report selection",

'overview_summary_title': "📊 Plan/Fact Summary for Today (regardless of approval)",
'overview_no_data': "No data available to build the summary.",

'loading_please_wait': 'Yuklanmoqda, iltimos kuting...',
        'overview_summary_title': 'Bugungi Reja/Fakt Hisoboti',
        'overview_discipline_summary': '📊 *{discipline}* (Jami: {people} kishi | O\'rt. Ish unumdorligi: {performance}%)',
        'overview_work_type_line': '{work_type}: F: {fact:.1f} / R: {plan:.1f} / Ish unumdorligi: {percent:.1f}%',
        'overview_select_chart_prompt': 'Diagrammani ko\'rish uchun yo\'nalishni tanlang:',
        'no_reports_for_other_disciplines': 'Boshqa yo\'nalishlar bo\'yicha bugun hisobotlar berilmadi.',
        'overview_no_data': 'Hozircha umumiy hisobot uchun ma\'lumotlar mavjud emas.',
        'error_generic': 'Xatolik yuz berdi. Iltimos, qayta urinib ko\'ring.',
        'back_button': '◀️ Orqaga',

    }
}

DEFAULT_LANGUAGE = 'ru'

# Вставьте этот код в конец файла localization.py, заменив старую версию

# Словарь для перевода данных из БД (названия работ, дисциплин и т.д.)
DATA_TRANSLATIONS = {
    # --- ДИСЦИПЛИНЫ ---
    'Механомонтаж': {'en': 'Mechanical Installation', 'uz': 'Mexanik montaj'},
    'Бетонные работы': {'en': 'Concrete Works', 'uz': 'Beton ishlari'},
    'КИПиА': {'en': 'Instrumentation & Automation', 'uz': 'O\'lchov asboblari va avtomatika'},
    'Металлоконструкция': {'en': 'Steel Structures', 'uz': 'Metall konstruksiyalar'},
    'Отделочные работы': {'en': 'Finishing Works', 'uz': 'Pardozlash ishlari'},
    'Трубопровод': {'en': 'Piping', 'uz': 'Quvurlar'},
    'Земляные работы': {'en': 'Earthworks', 'uz': 'Yer ishlari'},

    # --- ВИДЫ РАБОТ ---
    'МОНТАЖ СБОРНЫХ ЖЕЛЕЗОБЕТОННЫХ КОНСТРУКТИВНЫХ ЭЛЕМЕНТОВ ЗДАНИЙ И СООРУЖЕНИЙ: БАЛОК': {'en': 'Installation of precast reinforced concrete structural elements of buildings and structures: beams', 'uz': 'Bino va inshootlarning yig\'ma temir-beton konstruktiv elementlarini montaj qilish: to\'sinlar'},
    'УСТАНОВКА СБОРНЫХ ЖЕЛЕЗОБЕТОННЫХ ФУНДАМЕНТОВ': {'en': 'Installation of precast reinforced concrete foundations', 'uz': 'Yig\'ma temir-beton fundamentlarni o\'rnatish'},
    'МОНОЛИТНЫЕ ЖЕЛЕЗОБЕТОННЫЕ КОНСТРУКЦИИ': {'en': 'Monolithic reinforced concrete structures', 'uz': 'Monolit temir-beton konstruksiyalar'},
    'МОНТАЖ СБОРНЫХ ЖЕЛЕЗОБЕТОННЫХ КОЛОДЦЕВ': {'en': 'Installation of precast reinforced concrete manholes', 'uz': 'Yig\'ma temir-beton quduqlarni montaj qilish'},
    'УСТРОЙСТВО МОНОЛИТНЫХ ЖЕЛЕЗОБЕТОННЫХ КОЛОДЦЕВ': {'en': 'Construction of monolithic reinforced concrete manholes', 'uz': 'Monolit temir-beton quduqlarni qurish'},
    'УСТРОЙСТВО ЖЕЛЕЗОБЕТОННЫХ МОНОЛИТНЫХ ЛОТКОВ': {'en': 'Construction of reinforced concrete monolithic trays', 'uz': 'Temir-beton monolit lotoklarni qurish'},
    'НАСЕЧКА ЖЕЛЕЗОБЕТОННЫХ ФУНДАМЕНТОВ': {'en': 'Notching of reinforced concrete foundations', 'uz': 'Temir-beton fundamentlarga kertik ochish'},
    'УСТРОЙСТВО БЕТОННОЙ ПОДГОТОВКИ': {'en': 'Installation of concrete blinding', 'uz': 'Beton tayyorgarlik qurish'},
    'УСТРОЙСТВО БЕТОННОЙ ПОДЛИВКИ': {'en': 'Installation of concrete grout', 'uz': 'Beton quyma qurish'},
    'МОНТАЖ И ДЕМОНТАЖ ОПАЛУБКИ': {'en': 'Installation and dismantling of formwork', 'uz': 'Opalubkani montaj va demontaj qilish'},
    'УСТРОЙСТВО ЖЕЛЕЗОБЕТОННЫХ ФУНДАМЕНТОВ': {'en': 'Construction of reinforced concrete foundations', 'uz': 'Temir-beton fundamentlarni qurish'},
    'УСТРОЙСТВО БЕТОННЫХ ФУНДАМЕНТОВ ОБЩЕГО НАЗНАЧЕНИЯ ОБЪЕМОМ ДО 1 М3': {'en': 'Construction of general-purpose concrete foundations up to 1 m³', 'uz': 'Hajmi 1 m³ gacha bo\'lgan umumiy maqsadli beton fundamentlarni qurish'},
    'ВЯЗКА АРМАТУРНЫХ СТЕРЖНЕЙ ПОД ФУНДАМЕНТЫ, ПОЛЫ И ОТМОСТКИ': {'en': 'Tying of reinforcement bars for foundations, floors, and blind areas', 'uz': 'Fundamentlar, pollar va otmostkalar uchun armatura sterjenlarini bog\'lash'},
    'ВЯЗКА АРМАТУРНЫХ СТЕРЖНЕЙ ПОД КОЛОННЫ, СТЕНЫ, БАЛКИ, РИГЕЛИ, ПЕРЕКРЫТИЯ': {'en': 'Tying of reinforcement bars for columns, walls, beams, crossbars, and floor slabs', 'uz': 'Ustunlar, devorlar, to\'sinlar, rigellar, qoplamalar uchun armatura sterjenlarini bog\'lash'},
    'ИЗГОТОВЛЕНИЕ АРМАТУРНЫХ СТЕРЖНЕЙ': {'en': 'Fabrication of reinforcement bars', 'uz': 'Armatura sterjenlarini tayyorlash'},
    'МОНТАЖ АНКЕРНЫХ БОЛТОВ': {'en': 'Installation of anchor bolts', 'uz': 'Anker boltlarini montaj qilish'},
    'УСТАНОВКА ЗАКЛАДНЫХ ДЕТАЛЕЙ ДО 4 КГ': {'en': 'Installation of embedded parts up to 4 kg', 'uz': 'Og\'irligi 4 kg gacha bo\'lgan o\'rnatma detallarni o\'rnatish'},
    'УСТАНОВКА ЗАКЛАДНЫХ ДЕТАЛЕЙ СВЫШЕ 4 КГ': {'en': 'Installation of embedded parts over 4 kg', 'uz': 'Og\'irligi 4 kg dan yuqori bo\'lgan o\'rnatma detallarni o\'rnatish'},
    'ПРИГОТОВЛЕНИЕ ТЯЖЕЛОГО БЕТОНА': {'en': 'Preparation of heavy concrete', 'uz': 'Og\'ir beton tayyorlash'},
    'СВЕРЛЕНИЕ ОТВЕРСТИЙ В ЖЕЛЕЗОБЕТОННЫХ КОНСТРУКЦИЯХ': {'en': 'Drilling holes in reinforced concrete structures', 'uz': 'Temir-beton konstruksiyalarda teshik burg\'ulash'},
    'УСТАНОВКА АНКЕРНЫХ БОЛТОВ: ХИМИЧЕСКИХ': {'en': 'Installation of chemical anchor bolts', 'uz': 'Kimyoviy anker boltlarini o\'rnatish'},
    'УСТАНОВКА И ДЕМОНТАЖ ИНВЕНТАРНЫХ ЛЕСОВ': {'en': 'Installation and dismantling of inventory scaffolding', 'uz': 'Inventar havozalarni o\'rnatish va demontaj qilish'},
    'УСТРОЙСТВО ПОЛОВ БЕТОННЫХ ТОЛЩИНОЙ ДО 20 СМ': {'en': 'Construction of concrete floors up to 20 cm thick', 'uz': 'Qalinligi 20 sm gacha bo\'lgan beton pollarni qurish'},
    'АРМИРОВАНИЕ ПОДСТИЛАЮЩИХ СЛОЕВ И НАБЕТОНОК СЕТКОЙ ЗАВОДСКОГО ИЗГОТОВЛЕНИЯ': {'en': 'Reinforcement of sub-layers and concrete toppings with factory-made mesh', 'uz': 'Taglik qatlamlari va beton qoplamalarni zavodda tayyorlangan to\'r bilan armaturalash'},
    'ДЕМОНТАЖ ФУНДАМЕНТОВ ЖЕЛЕЗОБЕТОННЫХ': {'en': 'Dismantling of reinforced concrete foundations', 'uz': 'Temir-beton fundamentlarni demontaj qilish'},
    'СВЕРЛЕНИЕ ОТВЕРСТИЙ В БЕТОННЫХ КОНСТРУКЦИЯХ ПЕРФОРАТОРОМ ГЛУБИНОЙ 200 ММ ДО Ø 80 ММ': {'en': 'Drilling holes in concrete structures with a hammer drill, depth 200 mm, up to Ø 80 mm', 'uz': 'Beton konstruksiyalarda perforator bilan chuqurligi 200 mm, Ø 80 mm gacha teshik burg\'ulash'},
    'ШТРОБЛЕНИЕ БЕТОННЫХ СТЕН': {'en': 'Chasing of concrete walls', 'uz': 'Beton devorlarda shtroba ochish'},
    'УСТРОЙСТВО ДОРОГ ИЗ СБОРНЫХ ЖЕЛЕЗОБЕТОННЫХ ПЛИТ': {'en': 'Construction of roads from precast reinforced concrete slabs', 'uz': 'Yig\'ma temir-beton plitalardan yo\'l qurish'},
    'УСТРОЙСТВО ЖЕЛЕЗОБЕТОННЫХ СБОРНЫХ ЛОТКОВ': {'en': 'Construction of precast reinforced concrete trays', 'uz': 'Yig\'ma temir-beton lotoklarni qurish'},
    'УПЛОТНЕНИЕ ГРУНТА ЩЕБНЕМ ТОЛЩ. 10 СМ': {'en': 'Soil compaction with crushed stone, 10 cm thick', 'uz': 'Gruntni 10 sm qalinlikdagi shag\'al bilan zichlash'},
    'УСТРОЙСТВО ПОДСТИЛАЮЩИХ СЛОЕВ ВРУЧНУЮ (ЩЕБЕНОЧНЫХ, ПЕСЧАННЫХ, ГРАВИЙНЫХ)': {'en': 'Manual construction of sub-layers (crushed stone, sand, gravel)', 'uz': 'Taglik qatlamlarini qo\'lda qurish (shag\'al, qum, graviy)'},
    'ПЛАНИРОВКА ПЛОЩАДЕЙ РУЧНЫМ СПОСОБОМ': {'en': 'Manual area leveling', 'uz': 'Maydonlarni qo\'lda tekislash'},
    'ОБРАТНАЯ ЗАСЫПКА С УПЛОТНЕНИЕМ ВРУЧНУЮ': {'en': 'Manual backfilling with compaction', 'uz': 'Qo\'lda zichlagan holda qayta to\'ldirish'},
    'ДОРАБОТКА ГРУНТА ВРУЧНУЮ': {'en': 'Manual soil finishing', 'uz': 'Gruntni qo\'lda ishlov berib tugatish'},
    'ЗАСЫПКА ВРУЧНУЮ ТРАНШЕЙ': {'en': 'Manual backfilling of trenches', 'uz': 'Transheyalarni qo\'lda to\'ldirish'},
    'ДОРАБОТКА ГРУНТА ВРУЧНУЮ В ТРАНШЕЕ': {'en': 'Manual soil finishing in a trench', 'uz': 'Transheyada gruntni qo\'lda ishlov berib tugatish'},

    'ИЗГОТОВЛЕНИЕ МЕЛКИХ МЕТАЛЛОКОНСТРУКЦИЙ НА СТРОЙПЛОЩАДКЕ': {'en': 'Fabrication of small metal structures on the construction site', 'uz': 'Qurilish maydonchasida mayda metall konstruksiyalarni tayyorlash'},
    'МОНТАЖ ЛЕСТНИЦ, ПЛОЩАДОК, СТОЕК И ДР. МАЛОТОННАЖНЫХ КОНСТРУКЦИЙ НА СВАРКЕ': {'en': 'Installation of stairs, platforms, racks and other light-duty welded structures', 'uz': 'Zinapoyalar, maydonchalar, ustunlar va boshqa yengil payvandlangan konstruksiyalarni montaj qilish'},
    'МОНТАЖ МЕТАЛЛОКОНСТРУКЦИЙ': {'en': 'Installation of metal structures', 'uz': 'Metall konstruksiyalarni montaj qilish'},
    'ИЗГОТОВЛЕНИЕ МЕТАЛЛОКОНСТРУКЦИЙ': {'en': 'Fabrication of metal structures', 'uz': 'Metall konstruksiyalarni tayyorlash'},
    'МОНТАЖ ВНУТРЕННИХ СПЕЦИАЛИЗИРОВАННЫХ КОНСТРУКЦИЙ ОБОРУДОВАНИЯ': {'en': 'Installation of internal specialized equipment structures', 'uz': 'Uskunalarning ichki ixtisoslashtirilgan konstruksiyalarini montaj qilish'},
    'УСТРОЙСТВО БЕТОННОЙ ПОДЛИВКИ (УММР)': {'en': 'Installation of concrete grout (UMMR)', 'uz': 'Beton quyma qurish (UMMR)'},
    'МОНТАЖ АГРЕГАТОВ НАСОСНЫХ ЦЕНТРОБЕЖНЫХ': {'en': 'Installation of centrifugal pump units', 'uz': 'Markazdan qochma nasos agregatlarini montaj qilish'},
    'КОНВЕЙЕР ЛЕНТОЧНЫЙ СТАЦИОНАРНЫЙ': {'en': 'Stationary belt conveyor', 'uz': 'Statsionar lenta konveyeri'},
    'ФЛОТАЦИОННАЯ МАШИНА: МОНТАЖ': {'en': 'Flotation machine: installation', 'uz': 'Flotatsion mashina: montaj qilish'},
    'МОНТАЖ СТЕНКИ РЕЗЕРВУАРА (РУЛОННЫХ ЗАГОТОВОК)': {'en': 'Installation of tank wall (from rolled blanks)', 'uz': 'Rezervuar devorini montaj qilish (rulonli qoliplardan)'},
    'МОНТАЖ ДНИЩА ИЗ РУЛОННЫХ ЗАГОТОВОК ДЛЯ РЕЗЕРВУАРОВ': {'en': 'Installation of bottom from rolled blanks for tanks', 'uz': 'Rezervuarlar uchun rulonli qoliplardan tubini montaj qilish'},
    'МОНТАЖ КРОВЛИ ИЗ РУЛОННЫХ ЗАГОТОВОК ДЛЯ РЕЗЕРВУАРОВ': {'en': 'Installation of roof from rolled blanks for tanks', 'uz': 'Rezervuarlar uchun rulonli qoliplardan tomini montaj qilish'},
    'МЕЛЬНИЦА ШАРОВАЯ МОКРОГО ПОМОЛА: БАРАБАН ДИАМЕТРОМ СВЫШЕ 7000 ММ, ДЛИНА СВЫШЕ 13000 ММ': {'en': 'Wet grinding ball mill: drum diameter over 7000 mm, length over 13000 mm', 'uz': 'Ho\'l maydalash sharli tegirmoni: baraban diametri 7000 mm dan ortiq, uzunligi 13000 mm dan ortiq'},
    'ДРОБИЛКА КОНУСНАЯ ДЛЯ КРУПНОГО ДРОБЛЕНИЯ, ШИРИНА ЗАГРУЗОЧНОГО/РАЗГРУЗОЧНОГО ОТВЕРСТИЯ ММ 1500/200': {'en': 'Cone crusher for coarse crushing, loading/unloading opening width mm 1500/200', 'uz': 'Yirik maydalash uchun konusli maydalagich, yuklash/tushirish teshigi kengligi mm 1500/200'},
    'МОНТАЖ ОПОР ДЛЯ ТРУБОПРОВОДА': {'en': 'Installation of supports for pipeline', 'uz': 'Quvur uchun tayanchlarni montaj qilish'},
    'СВАРКА СТЫКОВ ТЕХНОЛОГИЧЕСКИХ ТРУБОПРОВОДОВ': {'en': 'Welding of technological pipeline joints', 'uz': 'Texnologik quvurlar choklarini payvandlash'},
    'МОНТАЖ ЗРА': {'en': 'Installation of shut-off and control valves', 'uz': 'Berkitish-rostlash armaturasini (ZRA) montaj qilish'},
    'ГИДРАВЛИЧЕСКОЕ ИСПЫТАНИЕ ТРУБОПРОВОДОВ': {'en': 'Hydraulic testing of pipelines', 'uz': 'Quvurlarni gidravlik sinovdan o\'tkazish'},
    'МОНТАЖ ПАРАФЛАНЦЕВОГО СОЕДИНЕНИЯ': {'en': 'Installation of a flange connection', 'uz': 'Flanesli birikmani montaj qilish'},


    'МОНТАЖ ИМПУЛЬСНОЙ ТРУБКИ': {'en': 'Installation of impulse tube', 'uz': 'Impuls trubkasini montaj qilish'},
    'МОНТАЖ МЕТАЛЛИЧЕСКИХ ШТАМПОВАННЫХ ЛОТКОВ': {'en': 'Installation of metal stamped trays', 'uz': 'Metall shtamplangan lotoklarni montaj qilish'},
    'ПРОКЛАДКА КАБЕЛЯ ПО ЛОТКАМ': {'en': 'Cable laying in trays', 'uz': 'Kabelni lotoklar bo\'ylab yotqizish'},
    'ПРОКЛАДКА КАБЕЛЯ ПО ТРАНШЕЕ': {'en': 'Cable laying in trench', 'uz': 'Kabelni transheya bo\'ylab yotqizish'},
    'МОНТАЖ ПРИБОРОВ': {'en': 'Installation of instruments', 'uz': 'Asboblarni montaj qilish'},
    'ПРОКЛАДКА КАБЕЛЯ В БЛОКАХ И КОРОБАХ': {'en': 'Cable laying in blocks and ducts', 'uz': 'Kabelni bloklar va koroblarda yotqizish'},
    'ЗАДЕЛКА ДЛЯ КАБЕЛЯ': {'en': 'Cable termination', 'uz': 'Kabel uchini ishlash'},
    'ПРИСОЕДИНЕНИЕ': {'en': 'Connection', 'uz': 'Ulanaish'},
    'МОНТАЖ КОРОБКИ': {'en': 'Junction box installation', 'uz': 'Qutini montaj qilish'},
    'МОНТАЖ ЩИТА': {'en': 'Panel board installation', 'uz': 'Shchitni montaj qilish'},
    'ПРОКЛАДКА ТРУБЫ ПНД': {'en': 'Laying of HDPE pipes', 'uz': 'PND quvurlarini yotqizish'},
    'СВЕРЛЕНИЕ В БЕТОННЫХ КОНСТРУКЦИЯХ ПЕРФОРАТОРОМ (ГЛУБИННОЕ)': {'en': 'Deep drilling in concrete structures with a hammer drill', 'uz': 'Beton konstruksiyalarda perforator bilan chuqur burg\'ulash'},
    'ШТРОБЛЕНИЕ БЕТОННЫХ СТЕН, ПОЛОВ И ПОТОЛКОВ': {'en': 'Chasing of concrete walls, floors, and ceilings', 'uz': 'Beton devorlar, pollar va shiftlarda shtroba ochish'},
    'МОНТАЖ ЛОТКОВ': {'en': 'Installation of trays', 'uz': 'Lotoklarni montaj qilish'},
    'УСТАНОВКА СТОЙКИ': {'en': 'Installation of a rack', 'uz': 'Ustunni o\'rnatish'},
    'УСТАНОВКА ПАНЕЛЕЙ': {'en': 'Installation of panels', 'uz': 'Panellarni o\'rnatish'},
    'УКЛАДКА МЕТАЛЛОРУКАВА': {'en': 'Laying of metal hose', 'uz': 'Metallorukavni yotqizish'},
    'ПРОКЛАДКА ТРУБЫ ГОФРИРОВАННОЙ ПВХ ДЛЯ ЗАЩИТЫ ПРОВОДОВ И КАБЕЛЕЙ': {'en': 'Laying of corrugated PVC pipe for wire and cable protection', 'uz': 'Simlar va kabellarni himoya qilish uchun gofralangan PVX quvurlarni yotqizish'},
    'ПРОКЛАДКА КАБЕЛЯ': {'en': 'Cable laying', 'uz': 'Kabel yotqizish'},
    'УКЛАДКА КАБЕЛЯ': {'en': 'Cable installation', 'uz': 'Kabelni joylashtirish'},
    'МОНТАЖ ПОЛОСЫ ЗАЗЕМЛЕНИЯ': {'en': 'Installation of grounding strip', 'uz': 'Yerga ulash polosasini montaj qilish'},
    'ПОДКЛЮЧЕНИЕ ИМПУЛЬСНОЙ ТРУБКИ': {'en': 'Connection of impulse tube', 'uz': 'Impuls trubkasini ulash'},
    'МОНТАЖ 1 КАБЕЛЬНОЙ МУФТЫ КИП': {'en': 'Installation of 1 I&C cable coupling', 'uz': '1 dona NAvaA kabel muftasini montaj qilish'},
    'МОНТАЖ 1 М ЗАЗЕМЛЯЮЩЕГО ПРОВОДНИКА ДЛЯ КИП': {'en': 'Installation of 1 m of grounding conductor for I&C', 'uz': 'NAvaA uchun 1 m yerga ulash o\'tkazgichini montaj qilish'},
    'РАЗДЕЛКА КОНЦОВ КАБЕЛЕЙ': {'en': 'Cable end stripping', 'uz': 'Kabel uchlarini ochish'},
    'РАСКЛЮЧЕНИЕ КАБЕЛЯ': {'en': 'Cable termination and connection', 'uz': 'Kabelni ulab chiqish'},
    'ПРОВЕРКА СОСТОЯНИЯ ИЗОЛЯЦИИ КАБЕЛЯ ДО И ПОСЛЕ ПРОКЛАДКИ': {'en': 'Checking the cable insulation condition before and after laying', 'uz': 'Kabel izolyatsiyasi holatini yotqizishdan oldin va keyin tekshirish'},

    'УСТАНОВКА ЖЕЛЕЗОБЕТОННЫХ ОГРАД ИЗ ПАНЕЛЕЙ : ПО БЕТОННЫМ СТОЛБАМ Ж/Б ПАНЕЛИ ДЛИНОЙ ДО 3 МЕТРОВ': {'en': 'Installation of reinforced concrete fences from panels: RC panels up to 3 meters long on concrete posts', 'uz': 'Panellardan temir-beton to\'siqlarni o\'rnatish: beton ustunlarga uzunligi 3 metrgacha bo\'lgan t/b panellar'},
    'УСТРОЙСТВО ДЕФОРМАЦИОННЫХ ШВОВ С ПРИМЕНЕНИЕМ ГЕРМЕТИКА': {'en': 'Installation of expansion joints using sealant', 'uz': 'Germetik yordamida deformatsion choklarni qurish'},
    'УСТРОЙСТВО ПРОКЛАДОЧНОЙ ГИДРОИЗОЛЯЦИИ ФУНДАМЕНТОВ РУЛОННЫМИ МАТЕРИАЛАМИ В ОДИН СЛОЙ НАСУХО': {'en': 'Installation of single-layer dry-laid roll waterproofing for foundations', 'uz': 'Fundamentlar uchun bir qatlamli quruq rulonli gidroizolyatsiya qurish'},
    'УСТРОЙСТВО ПОКРЫТИЙ ЩЕБЕНОЧНЫХ С ПРОПИТКОЙ БИТУМОМ': {'en': 'Construction of crushed stone pavements with bitumen impregnation', 'uz': 'Bitum shimdirilgan shag\'al qoplamalarni qurish'},
    'ПОСЕВ ГАЗОНОВ ВРУЧНУЮ С ПОДГОТОВКОЙ ПОЧВЫ': {'en': 'Manual lawn sowing with soil preparation', 'uz': 'Tuproqni tayyorlagan holda qo\'lda gazon ekish'},
    'ПОСАДКА ДЕРЕВЬЕВ С ПОДГОТОВКОЙ ПОСАДОЧНЫХ МЕСТ': {'en': 'Planting trees with preparation of planting holes', 'uz': 'Ekish joylarini tayyorlagan holda daraxt ekish'},
    'ФУТЕРОВКА СТЕН ТЕПЛОВЫХ АГРЕГАТОВ ПЛИТНЫМИ МАТЕРИАЛАМИ': {'en': 'Lining the walls of thermal units with slab materials', 'uz': 'Issiqlik agregatlari devorlarini plita materiallari bilan futerovka qilish'},
    'УСТАНОВКА ДВЕРНЫХ И ОКОННЫХ БЛОКОВ В СТЕНАХ': {'en': 'Installation of door and window units in walls', 'uz': 'Devorlarga eshik va deraza bloklarini o\'rnatish'},
    'ШТУКАТУРКА СТЕН': {'en': 'Wall plastering', 'uz': 'Devorlarni suvoq qilish'},
    'ШТУКАТУРКА ПОТОЛКОВ': {'en': 'Ceiling plastering', 'uz': 'Shiftlarni suvoq qilish'},
    'ШТУКАТУРКА ОТКОСОВ': {'en': 'Plastering of slopes', 'uz': 'Otko\'slarni suvoq qilish'},
    'ШПАТЛЕВКА БЕТОННЫХ ПОВЕРХНОСТЕЙ СТЕН, КОЛОНН': {'en': 'Filling of concrete surfaces of walls, columns', 'uz': 'Devorlar, ustunlarning beton yuzalarini shpatlyovka qilish'},
    'ШПАТЛЕВКА РИГЕЛЕЙ И ПОТОЛКОВ': {'en': 'Filling of crossbars and ceilings', 'uz': 'Rigellar va shiftlarni shpatlyovka qilish'},
    'ОКРАСКА ВОДОЭМУЛЬСИОННЫМИ СОСТАВАМИ ПО ШТУКАТУРКЕ СТЕН ВЫСОКОКАЧЕСТВЕННАЯ': {'en': 'High-quality water-based emulsion painting on plastered walls', 'uz': 'Suvoqlangan devorlarni yuqori sifatli suv-emulsiyali bo\'yoqlar bilan bo\'yash'},
    'ОКРАСКА ВОДОЭМУЛЬСИОННЫМИ СОСТАВАМИ РИГЕЛЕЙ, ПОТОЛКОВ': {'en': 'Water-based emulsion painting of crossbars, ceilings', 'uz': 'Rigellar, shiftlarni suv-emulsiyali bo\'yoqlar bilan bo\'yash'},
    'ОБЛИЦОВКА СТЕН КЕРАМИЧЕСКОЙ ПЛИТКОЙ': {'en': 'Wall cladding with ceramic tiles', 'uz': 'Devorlarni keramik plitkalar bilan qoplash'},
    'ОКЛЕЙКА СТЕН МОЮЩИМИСЯ ОБОЯМИ': {'en': 'Wallpapering walls with washable wallpaper', 'uz': 'Devorlarga yuviladigan gulqog\'oz yopishtirish'},
    'ОКРАСКА ПОВЕРХНОСТЕЙ СТЕН МАСЛЯННЫМИ СОСТАВАМИ ЗА ДВА РАЗА': {'en': 'Painting wall surfaces with oil-based compounds in two coats', 'uz': 'Devor yuzalarini ikki marta moyli bo\'yoqlar bilan bo\'yash'},
    'ОКРАСКА ПОВЕРХНОСТЕЙ ПОТОЛКОВ МАСЛЯННЫМИ СОСТАВАМИ ЗА ДВА РАЗА': {'en': 'Painting ceiling surfaces with oil-based compounds in two coats', 'uz': 'Shift yuzalarini ikki marta moyli bo\'yoqlar bilan bo\'yash'},
    'ОТДЕЛКА СТЕН ДЕКОРАТИВНЫМ ПОКРЫТИЕМ "ТРАВЕРТИН" С НАНЕСЕНИЕМ РИСУНКА И ПОЛИРОВКОЙ ПОВЕРХНОСТИ РУЧНЫМ СПОСОБОМ': {'en': 'Finishing walls with "Travertine" decorative coating with pattern application and manual surface polishing', 'uz': 'Devorlarni "Travertin" dekorativ qoplamasi bilan bezash, rasm chizish va yuzani qo\'lda silliqlash'},
    'УСТРОЙСТВО ПЕРЕГОРОДОК С ОДИНАРНЫМ МЕТАЛЛИЧЕСКИМ КАРКАСОМ И ДВУХСЛОЙНОЙ ОБШИВКОЙ ГИПСОКАРТОННЫМИ ПЛИТАМИ С ОБЕИХ СТОРОН С УТЕПЛЕНИЕМ': {'en': 'Installation of partitions with a single metal frame and double-layer gypsum board sheathing on both sides with insulation', 'uz': 'Bir qavatli metall karkasli va ikki tomondan gipsokarton plitalar bilan ikki qatlamli qoplangan, утеплитель bilan to\'siqlar qurish'},
    'ОБЛИЦОВКА СТЕН ГИПСОКАРТОННЫМИ ЛИСТАМИ В ОДИН СЛОЙ С УТЕПЛЕНИЕМ': {'en': 'Wall cladding with single-layer gypsum boards with insulation', 'uz': 'Devorlarni bir qatlamli gipsokarton listlar bilan утеплитель bilan qoplash'},
    'УСТРОЙСТВО ПОДВЕСНОГО ПОТОЛКА ГИПСОКАРТОННЫМИ ПЛИТАМИ ПО МЕТАЛЛИЧЕСКИМ НЕСУЩИМ КОНСТРУКЦИЯМ': {'en': 'Installation of suspended ceilings with gypsum boards on metal supporting structures', 'uz': 'Metall ko\'taruvchi konstruksiyalarga gipsokarton plitalardan osma shiftlar qurish'},
    'УСТРОЙСТВО ПОДВЕСНЫХ ПОТОЛКОВ ТИПА "АРМСТРОНГ"': {'en': 'Installation of "Armstrong" type suspended ceilings', 'uz': '"Armstrong" turidagi osma shiftlarni qurish'},
    'ОБЛИЦОВКА ФАСАДА ПАНЕЛЯМИ "АЛЮПАН" ИЛИ "АЛЮКОБОНД" С УСТРОЙСТВОМ КАРКАСА': {'en': 'Facade cladding with "Alupan" or "Alucobond" panels with frame installation', 'uz': 'Fasadni karkas o\'rnatish bilan "Alupan" yoki "Alucobond" panellari bilan qoplash'},
    'УСТРОЙСТВО ПОКРЫТИЙ ПОЛОВ ИЗ КЕРАМИЧЕСКИХ ПЛИТОК': {'en': 'Installation of ceramic tile flooring', 'uz': 'Keramik plitkalardan pol qoplamalarini qurish'},
    'УСТРОЙСТВО ПОКРЫТИЙ ПОЛОВ ИЗ ЛИНОЛЕУМА И КОВРОЛИНА С ПЛИНТУСОМ': {'en': 'Installation of linoleum and carpet flooring with skirting', 'uz': 'Plintus bilan linoleum va kovrolindan pol qoplamalarini qurish'},
    'УСТРОЙСТВО СТЯЖЕК ТОЛЩИНОЙ ДО 10 СМ': {'en': 'Installation of screeds up to 10 cm thick', 'uz': 'Qalinligi 10 sm gacha bo\'lgan styajkalarni qurish'},
    'УСТРОЙСТВО ПОКРЫТИЙ ПОЛОВ ИЗ ЛАМИНАТА': {'en': 'Installation of laminate flooring', 'uz': 'Laminatdan pol qoplamalarini qurish'},
    'УСТРОЙСТВО НАЛИВНЫХ ПОЛОВ': {'en': 'Installation of self-leveling floors', 'uz': 'Quyma pollarni qurish'},
    'УСТРОЙСТВО ПОКРЫТИЙ ИЗ МОЗАИЧНОЙ ПЛИТКИ ТОЛЩ. 25ММ': {'en': 'Installation of terrazzo tile flooring, 25mm thick', 'uz': 'Qalinligi 25 mm bo\'lgan mozaik plitkalardan qoplamalarni qurish'},
    'УСТРОЙСТВО ФАЛЬШПОЛА ТОЛЩ. 75 ММ': {'en': 'Installation of raised floor, 75 mm thick', 'uz': 'Qalinligi 75 mm bo\'lgan soxta pollarni qurish'},
    'УСТРОЙСТВО СТЯЖКИ КРОВЛИ ТОЛЩ. 20 ММ': {'en': 'Installation of roof screed, 20 mm thick', 'uz': 'Qalinligi 20 mm bo\'lgan tom styajkasini qurish'},
    'УСТРОЙСТВО КРОВЕЛЬ СКАТНЫХ ИЗ НАПЛАВЛЯЕМЫХ МАТЕРИАЛОВ В ТРИ СЛОЯ': {'en': 'Installation of pitched roofs from built-up roll materials in three layers', 'uz': 'Uch qatlamli yopma materiallardan nishabli tomlarni qurish'},
    'КЛАДКА АРМИРОВАННЫХ СТЕН ИЗ КИРПИЧА': {'en': 'Laying of reinforced brick walls', 'uz': 'G\'ishtdan armaturalangan devorlarni terish'},
    'КЛАДКА ПЕРЕГОРОДОК ИЗ КИРПИЧА АРМИРОВАННЫХ ТОЛЩИНОЙ В 1/2 КИРПИЧА': {'en': 'Laying of reinforced brick partitions, 1/2 brick thick', 'uz': 'Qalinligi 1/2 g\'isht bo\'lgan armaturalangan g\'isht to\'siqlarni terish'},
    'УСТРОЙСТВО ДЕРЕВЯННЫХ КАРКАСОВ КРОВЛИ': {'en': 'Installation of wooden roof frames', 'uz': 'Tomning yog\'och karkaslarini qurish'},
    'ГИДРОИЗОЛЯЦИЯ ОКЛЕЕЧНАЯ В ДВА СЛОЯ': {'en': 'Two-layer bonded waterproofing', 'uz': 'Ikki qatlamli yopishtiriladigan gidroizolyatsiya'},
    'ГИДРОИЗОЛЯЦИЯ ОБМАЗОЧНАЯ БИТУМНАЯ В ДВА СЛОЯ': {'en': 'Two-layer bitumen mastic waterproofing', 'uz': 'Ikki qatlamli bitumli surtma gidroizolyatsiya'},
    'ПРИГОТОВЛЕНИЕ ТЯЖЕЛЫХ ОТДЕЛОЧНЫХ РАСТВОРОВ': {'en': 'Preparation of heavy finishing mortars', 'uz': 'Og\'ir pardozlash qorishmalarini tayyorlash'},
    'МОНТАЖ ПОКРЫТИЯ ИЗ ПРОФЛИСТА: КРОВЕЛЬНОГО': {'en': 'Installation of profiled sheet covering: roofing', 'uz': 'Proflistdan qoplama montaj qilish: tom uchun'},
    'МОНТАЖ ПОКРЫТИЯ ИЗ ПРОФЛИСТА: СТЕНОВОГО': {'en': 'Installation of profiled sheet covering: wall', 'uz': 'Proflistdan qoplama montaj qilish: devor uchun'},
    'МОНТАЖ МЕТАЛЛИЧЕСКИХ ВОРОТ И ДВЕРЕЙ': {'en': 'Installation of metal gates and doors', 'uz': 'Metall darvoza va eshiklarni montaj qilish'},
    'МОНТАЖ КОЛЮЧЕЙ ПРОВОЛОКИ': {'en': 'Installation of barbed wire', 'uz': 'Tikanli simni montaj qilish'},
    'УСТРОЙСТВО ОГРАЖДЕНИЙ: ИЗ МЕТАЛЛИЧЕСКИХ ПАНЕЛЕЙ ПО Ж/Б СТОЛБАМ': {'en': 'Installation of fences: from metal panels on reinforced concrete posts', 'uz': 'To\'siqlar qurish: t/b ustunlarga metall panellardan'},
    'УСТРОЙСТВО ОГРАЖДЕНИЙ: ИЗ МЕТАЛЛИЧЕСКИХ ПАНЕЛЕЙ ПО МЕТАЛЛИЧЕСКИМ СТОЛБАМ': {'en': 'Installation of fences: from metal panels on metal posts', 'uz': 'To\'siqlar qurish: metall ustunlarga metall panellardan'},
    'УСТРОЙСТВО ОГРАЖДЕНИЙ: УСТАНОВКА ВОРОТ СЕТЧАТЫХ': {'en': 'Installation of fences: installation of mesh gates', 'uz': 'To\'siqlar qurish: to\'rli darvozalarni o\'rnatish'},
    'УСТРОЙСТВО ОГРАЖДЕНИЙ: УСТАНОВКА КАЛИТОК СЕТЧАТЫХ': {'en': 'Installation of fences: installation of mesh wickets', 'uz': 'To\'siqlar qurish: to\'rli eshikchalarni o\'rnatish'},
    'ИЗГОТОВЛЕНИЕ ПОЛОТЕН (ВОРОТ, КАЛИТОК) ОГРАЖДЕНИЙ': {'en': 'Fabrication of fence panels (gates, wickets)', 'uz': 'To\'siqlar polotnolarini (darvoza, eshikcha) tayyorlash'},
    'УСТРОЙСТВО СЭНДВИЧ-ПАНЕЛЕЙ : СТЕНЫ': {'en': 'Installation of sandwich panels: walls', 'uz': 'Sendvich-panellarni qurish: devorlar'},
    'УСТРОЙСТВО СЭНДВИЧ-ПАНЕЛЕЙ : КРОВЛИ': {'en': 'Installation of sandwich panels: roofing', 'uz': 'Sendvich-panellarni qurish: tom'},
    'УСТРОЙСТВО МЕЛКИХ ПОКРЫТИЙ (ПАРАПЕТЫ, СВЕСЫ, ОБДЕЛКИ, ЖЕЛОБЫ)': {'en': 'Installation of small coverings (parapets, overhangs, flashings, gutters)', 'uz': 'Mayda qoplamalarni qurish (parapetlar, karnizlar, bezaklar, tarnovlar)'},
    'ОБЛИЦОВКА СТЕН ДЕКОРАТИВНЫМИ ПЛАСТИКОВЫМИ И МДФ ПАНЕЛЯМИ С УСТРОЙСТВОМ С КАРКАСА БЕЗ ОТНОСА ОТ СТЕНЫ': {'en': 'Wall cladding with decorative plastic and MDF panels with frame installation flush to the wall', 'uz': 'Devorlarni dekorativ plastik va MDF panellari bilan karkas o\'rnatib, devordan masofasiz qoplash'},
    'ОБЛИЦОВКА ПОТОЛКА ДЕКОРАТИВНЫМИ ПЛАСТИКОВЫМИ И МДФ ПАНЕЛЯМИ С УСТРОЙСТВОМ КАРКАСА БЕЗ ОТНОСА ОТ ПОТОЛКА': {'en': 'Ceiling cladding with decorative plastic and MDF panels with frame installation flush to the ceiling', 'uz': 'Shiftni dekorativ plastik va MDF panellari bilan karkas o\'rnatib, shiftdan masofasiz qoplash'},
    'УСТРОЙСТВО ПОДВЕСНЫХ ПОТОЛКОВ: РЕЕЧНЫХ АЛЮМИНИЕВЫХ И КАССЕТНЫХ': {'en': 'Installation of suspended ceilings: slatted aluminum and cassette', 'uz': 'Osma shiftlarni qurish: reykali alyuminiy va kassetali'},
    'ОБЛИЦОВКА ФАСАДОВ КЕРАМОГРАНИТНЫМИ ПЛИТАМИ НА ЦЕМЕНТНОМ РАСТВОРЕ С ЗАТИРКОЙ ШВОВ': {'en': 'Facade cladding with porcelain stoneware tiles on cement mortar with joint grouting', 'uz': 'Fasadlarni sementli qorishmaga keromogranit plitalar bilan choklarini to\'ldirib qoplash'},
    'НАРУЖНАЯ ОБЛИЦОВКА ФАСАДОВ САЙДИНГОМ (КЕРАМОСАЙДИНГ, САЙДИНГ ИЗ ДРЕВЕСИНЫ)': {'en': 'Exterior facade cladding with siding (ceramic siding, wood siding)', 'uz': 'Fasadlarni sayding bilan tashqi qoplash (keramosayding, yog\'och sayding)'},
    'НАВЕСКА ВОДОСТОЧНЫХ ТРУБ': {'en': 'Hanging of downpipes', 'uz': 'Suv oqizish quvurlarini osish'},
    'КЛАДКА СТЕН И ПЕРЕГОРОДОК ИЗ ЛЕГКОБЕТОННЫХ КАМНЕЙ, ГАЗОБЛОКОВ БЕЗ ОБЛИЦОВКИ)': {'en': 'Laying of walls and partitions from lightweight concrete blocks, aerated concrete blocks without cladding', 'uz': 'Yengil beton toshlardan, gazobloklardan devor va to\'siqlarni qoplamasiz terish'},
    'УСТРОЙСТВО ДЕФОРМАЦИОННЫХ ШВОВ С ПРИМЕНЕНИЕМ РЕЗИНОВЫХ ПРОКЛАДОК, ЦЕМЕНТНЫХ РАСТВОРОВ': {'en': 'Installation of expansion joints using rubber gaskets, cement mortars', 'uz': 'Rezina prokladkalar, sementli qorishmalar yordamida deformatsion choklarni qurish'},
    'УСТРОЙСТВО ПОКРЫТИЙ ПОЛОВ ИЗ ДОСОК ПАРКЕТНЫХ (ДОЩАТЫХ, ИЗ БРУСКОВ)': {'en': 'Installation of flooring from parquet boards (plank, block)', 'uz': 'Parket taxtalaridan (taxtali, brusokli) pol qoplamalarini qurish'},
    'УСТАНОВКА ПОТОЛОЧНЫХ ПЛИНТУСОВ': {'en': 'Installation of ceiling skirtings', 'uz': 'Shift plintuslarini o\'rnatish'},
    'УСТРОЙСТВО КАРКАСОВ ЗДАНИЙ ИЗ ТОНКОЛИСТОВОЙ СТАЛИ (ЛСТК) НА БОЛТОВЫХ СОЕДИНЕНИЯХ': {'en': 'Construction of building frames from light gauge steel framing (LGSF) with bolted connections', 'uz': 'Yengil po\'lat yupqa profilli (LSTK) bino karkaslarini boltli birikmalarda qurish'},
    'УСТРОЙСТВО НАРУЖНОЙ ТЕПЛОИЗОЛЯЦИИ ЗДАНИЙ С ТОНКОЙ ШТУКАТУРКОЙ ПО УТЕПЛИТЕЛЮ ТОЛЩИНОЙ ПЛИТ ДО: 100 ММ': {'en': 'Installation of external thermal insulation of buildings with thin plaster over insulation with slab thickness up to: 100 mm', 'uz': 'Binolarning tashqi issiqlik izolyatsiyasini утеплитель ustidan yupqa suvoq bilan, plita qalinligi 100 mm gacha qurish'},
    'МОНТАЖ ПЕРЕГОРОДОК ИЗ АЛЮМИНИЕВЫХ СПЛАВОВ СБОРНО-РАЗБОРНЫХ С ОСТЕКЛЕНИЕМ': {'en': 'Installation of demountable aluminum alloy partitions with glazing', 'uz': 'Oynali yig\'ma-ajraladigan alyuminiy qotishmalaridan to\'siqlarni montaj qilish'},
    'УСТРОЙСТВО ПЕРЕГОРОДОК ИЗ МДФ-ПАНЕЛЕЙ, АЛЮМИНИЯ, ПВХ ПРОФИЛЕЙ': {'en': 'Installation of partitions from MDF panels, aluminum, PVC profiles', 'uz': 'MDF-panellar, alyuminiy, PVX profillardan to\'siqlar qurish'},
    'ОКРАСКА ПОВЕРХНОСТЕЙ МЕТАЛЛИЧЕСКИХ ВРУЧНУЮ, ВКЛЮЧАЯ ПОДГОТОВКУ ПОВЕРХНОСТИ': {'en': 'Manual painting of metal surfaces, including surface preparation', 'uz': 'Metall yuzalarni qo\'lda bo\'yash, shu jumladan yuzani tayyorlash'},
    'УСТРОЙСТВО ПЛИНТУСОВ ПВХ НА ВИНТАХ САМОНАРЕЗАЮЩИХ': {'en': 'Installation of PVC skirtings on self-tapping screws', 'uz': 'PVX plintuslarni o\'z-o\'zidan kesuvchi vintlarga o\'rnatish'},
    'УСТАНОВКА ПОДОКОННЫХ ДОСОК ИЗ ПВХ': {'en': 'Installation of PVC window sills', 'uz': 'PVX deraza tokchalarini o\'rnatish'},
    'УСТРОЙСТВО ДЕКОРАТИВНОГО ПОКРЫТИЯ ТИПА "OTTOCENTO"': {'en': 'Installation of "Ottocento" type decorative coating', 'uz': '"Ottocento" turidagi dekorativ qoplamani qurish'},

    'ПРОЧИЕ РАБОТЫ (УСТРАНЕНИЕ ЗАМЕЧАНИЙ, ОЧИСТКА ТЕРРИТОРИИ, ПОДСОБНИЧЕСТВО И Т.Д.)': {'en': 'Miscellaneous works (rectification of defects, site cleaning, auxiliary work, etc.)', 'uz': 'Boshqa ishlar (kamchiliklarni bartaraf etish, hududni tozalash, yordamchi ishlar va h.k.)'},

    'ТН': {'en': 't (tonne)', 'uz': 't (tonna)'},
    'М3': {'en': 'm³ (cubic meter)', 'uz': 'm³ (kubometr)'},
    'М2': {'en': 'm² (square meter)', 'uz': 'm² (kvadrat metr)'},
    'М': {'en': 'm (meter)', 'uz': 'm (metr)'},
    'ШТ': {'en': 'pcs (pieces)', 'uz': 'dona'},
    'чел.час': {'en': 'man-hour', 'uz': 'odam-soat'},
    'компл': {'en': 'set', 'uz': 'kompl (komplekt)'},
    'п.м': {'en': 'lm (linear meter)', 'uz': 'p.m (pogon metr)'},
    'кг': {'en': 'kg (kilogram)', 'uz': 'kg (kilogramm)'},


}

def get_data_translation(original_text: str, lang_code: str = 'ru') -> str:
    """
    Ищет перевод для данных. Если перевода нет, возвращает оригинальный текст.
    """
    # Язык по умолчанию 'ru', для него перевод не нужен
    if lang_code == 'ru' or not original_text:
        return original_text
    
    # Убираем лишние пробелы с краев для надежного поиска в словаре
    cleaned_text = original_text.strip()
    
    # Ищем перевод в словаре. Если не находим, возвращаем исходный очищенный текст.
    return DATA_TRANSLATIONS.get(cleaned_text, {}).get(lang_code, cleaned_text)

def get_text(key: str, lang_code: str = DEFAULT_LANGUAGE) -> str:
    """
    Возвращает переведенную строку по ключу и коду языка.
    Если перевод не найден, возвращает ключ как заглушку.
    """
    if not lang_code:
        lang_code = DEFAULT_LANGUAGE
    # Возвращает перевод для нужного языка. Если язык не найден, использует язык по умолчанию.
    return TRANSLATIONS.get(lang_code, TRANSLATIONS[DEFAULT_LANGUAGE]).get(key, f"_{key}_")